# Generated by Django 6.0.4 on 2026-05-12 00:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conduces', '0025_empresa_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('materia_prima', 'Materia prima'), ('produccion', 'Producción'), ('activo', 'Activo'), ('oficina', 'Material de oficina'), ('limpieza', 'Limpieza'), ('otro', 'Otro')], default='materia_prima', max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('empresa', 'nombre', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=180, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('materia_prima', 'Materia prima'), ('producto_terminado', 'Producto terminado'), ('activo', 'Activo'), ('oficina', 'Material de oficina'), ('limpieza', 'Limpieza'), ('otro', 'Otro')], default='materia_prima', max_length=30)),
                ('unidad_medida', models.CharField(choices=[('lb', 'Libras'), ('oz', 'Onzas'), ('g', 'Gramos'), ('kg', 'Kilogramos'), ('unidad', 'Unidad'), ('galon', 'Galón'), ('litro', 'Litro'), ('paquete', 'Paquete'), ('caja', 'Caja')], default='lb', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoriainventario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('empresa', 'nombre', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='PrestamoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entregado', 'De la panadería a terceros'), ('recibido', 'De terceros a la panadería')], max_length=20)),
                ('tercero', models.CharField(max_length=180)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('responsable_entrega', models.CharField(blank=True, max_length=180, null=True)),
                ('responsable_recibe', models.CharField(blank=True, max_length=180, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('cerrado', 'Cerrado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
            ],
            options={
                'ordering': ['-fecha_prestamo', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('produccion', 'Producción'), ('merma', 'Merma'), ('prestamo_entregado', 'Préstamo entregado'), ('prestamo_recibido', 'Préstamo recibido'), ('devolucion_prestamo', 'Devolución préstamo')], max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('costo_estimado', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
            ],
            options={
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('pan', 'Pan'), ('pan_vegetales', 'Pan con vegetales'), ('bizcocho', 'Bizcocho'), ('galleta', 'Galleta nutritiva'), ('otro', 'Otro')], max_length=30)),
                ('unidad_resultado', models.CharField(default='unidad', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('rendimiento_unidades', models.DecimalField(decimal_places=4, max_digits=14)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productoproduccion')),
            ],
            options={
                'ordering': ['producto__nombre', 'nombre'],
                'unique_together': {('empresa', 'producto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ProduccionProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_unidades', models.DecimalField(decimal_places=4, max_digits=14)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('ejecutada', 'Ejecutada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('ejecutada_en', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoproduccion')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.receta')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad_medida', models.CharField(default='lb', max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.receta')),
            ],
            options={
                'ordering': ['materia_prima__nombre'],
                'unique_together': {('receta', 'materia_prima')},
            },
        ),
    ]
