# Generated by Django 6.0.4 on 2026-05-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0025_empresa_logo'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoinventario',
            old_name='costo_unitario',
            new_name='precio_unitario_compra',
        ),
        migrations.AlterUniqueTogether(
            name='productoinventario',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddField(
            model_name='productoinventario',
            name='cantidad_por_empaque',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name='productoinventario',
            name='porcentaje_itbis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productoinventario',
            name='proveedor',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='productoinventario',
            name='unidad_compra',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='productoinventario',
            name='unidad_medida',
            field=models.CharField(choices=[('lb', 'Libras'), ('oz', 'Onzas'), ('g', 'Gramos'), ('kg', 'Kilogramos'), ('unidad', 'Unidad'), ('galon', 'Galón'), ('litro', 'Litro'), ('paquete', 'Paquete'), ('caja', 'Caja'), ('yarda', 'Yarda')], default='lb', max_length=20),
        ),
    ]
