# Generated by Django 6.0.4 on 2026-05-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0025_empresa_logo'),
        ('inventario', '0002_rename_costo_unitario_productoinventario_precio_unitario_compra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('factura', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.productoinventario')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'fecha_ingreso'],
            },
        ),
    ]
