# Generated by Django 6.0.4 on 2026-05-15 01:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_loteinventario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleordencompra',
            options={'ordering': ['producto__nombre', 'producto_manual']},
        ),
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='costo_estimado',
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='cantidad_compra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='cantidad_faltante',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='cantidad_necesaria',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='cantidad_sugerida_compra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='itbis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='porcentaje_itbis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='precio_unitario_compra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='producto_manual',
            field=models.CharField(blank=True, help_text='Usar solo si el producto no está registrado en inventario.', max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='unidad_base',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='unidad_compra',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='itbis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario'),
        ),
    ]
