# Generated by Django 6.0.4 on 2026-05-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_detalleordencompra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='porcentaje_variacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje adicional para cubrir merma, variación de peso o producción manual.', max_digits=5),
        ),
    ]
