# Generated by Django 6.0.4 on 2026-05-16 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_receta_porcentaje_variacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='inventario_actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='recibida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('entrada_compra', 'Entrada por compra'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('produccion', 'Producción'), ('merma', 'Merma'), ('prestamo_entregado', 'Préstamo entregado'), ('prestamo_recibido', 'Préstamo recibido'), ('devolucion_prestamo', 'Devolución préstamo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('recibida', 'Recibida'), ('parcial', 'Recibida parcial'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
    ]
