# Generated by Django 6.0.4 on 2026-05-17 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0026_dianodocencia'),
        ('inventario', '0006_ordencompra_fecha_recepcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriainventario',
            name='tipo',
            field=models.CharField(choices=[('materia_prima', 'Materia prima'), ('produccion', 'Producción'), ('activo', 'Activo'), ('empaque', 'Empaque'), ('consumible', 'Consumible'), ('oficina', 'Material de oficina'), ('limpieza', 'Limpieza'), ('transporte', 'Transporte'), ('otro', 'Otro')], default='materia_prima', max_length=30),
        ),
        migrations.CreateModel(
            name='DetalleConsumoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_manuales', to='inventario.produccionprogramada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionConsumoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto_menu', models.CharField(max_length=180)),
                ('raciones', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cantidad_proyectada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cantidad_real', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('diferencia', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('porcentaje_diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.receta')),
            ],
            options={
                'ordering': ['-fecha', 'materia_prima__nombre'],
                'unique_together': {('empresa', 'fecha', 'producto_menu', 'materia_prima')},
            },
        ),
    ]
