# Generated by Django 6.0.4 on 2026-05-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_categoriainventario_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinventario',
            name='afecta_produccion',
            field=models.BooleanField(default=True, help_text='Indica si este producto debe limitar la proyección automática de producción.'),
        ),
        migrations.AddField(
            model_name='productoinventario',
            name='clasificacion_operativa',
            field=models.CharField(choices=[('materia_prima', 'Materia prima de producción'), ('empaque', 'Empaque'), ('consumible', 'Consumible operativo'), ('limpieza', 'Limpieza'), ('administrativo', 'Administrativo'), ('transporte', 'Transporte'), ('otro', 'Otro')], default='materia_prima', max_length=30),
        ),
        migrations.AlterField(
            model_name='productoinventario',
            name='tipo',
            field=models.CharField(choices=[('materia_prima', 'Materia prima'), ('producto_terminado', 'Producto terminado'), ('empaque', 'Empaque'), ('consumible', 'Consumible'), ('activo', 'Activo'), ('oficina', 'Material de oficina'), ('limpieza', 'Limpieza'), ('transporte', 'Transporte'), ('otro', 'Otro')], default='materia_prima', max_length=30),
        ),
    ]
