# Generated by Django 6.0.4 on 2026-07-29 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_pedido_historialestadopedido_detallepedido_and_more'),
        ('conduces', '0026_dianodocencia'),
        ('inventario', '0008_productoinventario_afecta_produccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlanProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cantidad_planificada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('fecha_requerida', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('detalle_pedido_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.detallepedido')),
                ('pedido_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
            ],
            options={
                'ordering': ['producto_terminado__nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('fecha_programada', models.DateField()),
                ('turno', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche'), ('UNICO', 'Único')], default='UNICO', max_length=10)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('cantidad_planificada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cantidad_iniciada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cantidad_producida', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cantidad_rechazada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADA', 'Programada'), ('LIBERADA', 'Liberada'), ('EN_PROCESO', 'En proceso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_prod_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_prod_creadas', to=settings.AUTH_USER_MODEL)),
                ('detalle_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='inventario.detalleplanproduccion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='conduces.empresa')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_programada', '-id'],
                'permissions': [('programar_ordenproduccion', 'Puede programar órdenes de producción'), ('iniciar_ordenproduccion', 'Puede iniciar órdenes de producción'), ('completar_ordenproduccion', 'Puede completar órdenes de producción'), ('cancelar_ordenproduccion', 'Puede cancelar órdenes de producción')],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADA', 'Programada'), ('LIBERADA', 'Liberada'), ('EN_PROCESO', 'En proceso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADA', 'Programada'), ('LIBERADA', 'Liberada'), ('EN_PROCESO', 'En proceso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='inventario.ordenproduccion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('fecha_plan', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADO', 'Generado'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('PEDIDOS', 'Pedidos')], default='MANUAL', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_prod_actualizados', to=settings.AUTH_USER_MODEL)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_prod_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_prod_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_produccion', to='conduces.empresa')),
            ],
            options={
                'ordering': ['-fecha_plan', '-id'],
                'permissions': [('aprobar_planproduccion', 'Puede aprobar planes de producción'), ('cancelar_planproduccion', 'Puede cancelar planes de producción')],
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='inventario.planproduccion'),
        ),
        migrations.CreateModel(
            name='NecesidadMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_teorica', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('porcentaje_merma_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cantidad_con_merma', models.DecimalField(decimal_places=4, max_digits=16)),
                ('fecha_requerida', models.DateField()),
                ('estado', models.CharField(choices=[('CALCULADA', 'Calculada'), ('REVISADA', 'Revisada'), ('CUBIERTA', 'Cubierta'), ('INSUFICIENTE', 'Insuficiente'), ('CANCELADA', 'Cancelada')], default='CALCULADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='necesidades_produccion', to='inventario.productoinventario')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.productoinventario')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='necesidades', to='inventario.ordenproduccion')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='necesidades', to='inventario.planproduccion')),
            ],
        ),
        migrations.AddField(
            model_name='detalleplanproduccion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.planproduccion'),
        ),
        migrations.CreateModel(
            name='RecetaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=180)),
                ('version', models.PositiveIntegerField(default=1)),
                ('rendimiento_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad_rendimiento', models.CharField(max_length=30)),
                ('porcentaje_merma_estimada', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tiempo_preparacion_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('tiempo_produccion_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=False)),
                ('fecha_vigencia_desde', models.DateField()),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_prod_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_prod_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_produccion', to='conduces.empresa')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_produccion', to='inventario.productoinventario')),
            ],
            options={
                'ordering': ['producto_terminado__nombre', '-version'],
                'permissions': [],
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.recetaproduccion'),
        ),
        migrations.CreateModel(
            name='DetalleRecetaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('porcentaje_merma', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('es_opcional', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uso_en_recetas_produccion', to='inventario.productoinventario')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='inventario.recetaproduccion')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='detalleplanproduccion',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.recetaproduccion'),
        ),
        migrations.AddConstraint(
            model_name='planproduccion',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='inv_planprod_empresa_numero_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recetaproduccion',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='inv_recprod_empresa_codigo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recetaproduccion',
            constraint=models.UniqueConstraint(fields=('empresa', 'producto_terminado', 'version'), name='inv_recprod_producto_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recetaproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('rendimiento_base__gt', 0)), name='inv_recprod_rendimiento_positivo'),
        ),
        migrations.AddConstraint(
            model_name='recetaproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_merma_estimada__gte', 0), ('porcentaje_merma_estimada__lte', 100)), name='inv_recprod_merma_rango'),
        ),
        migrations.AddConstraint(
            model_name='ordenproduccion',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='inv_ordenprod_empresa_numero_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ordenproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_planificada__gt', 0)), name='inv_ordenprod_planificada_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ordenproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_producida__gte', 0), ('cantidad_rechazada__gte', 0)), name='inv_ordenprod_cantidades_no_negativas'),
        ),
        migrations.AddConstraint(
            model_name='detallerecetaproduccion',
            constraint=models.UniqueConstraint(fields=('receta', 'materia_prima'), name='inv_detrecprod_materia_uniq'),
        ),
        migrations.AddConstraint(
            model_name='detallerecetaproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='inv_detrecprod_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detallerecetaproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_merma__gte', 0), ('porcentaje_merma__lte', 100)), name='inv_detrecprod_merma_rango'),
        ),
        migrations.AddConstraint(
            model_name='detalleplanproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_planificada__gt', 0)), name='inv_detplan_cantidad_positiva'),
        ),
    ]
