# Generated by Django 6.0.4 on 2026-07-29 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0026_dianodocencia'),
        ('inventario', '0009_detalleplanproduccion_ordenproduccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReservaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reservada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cantidad_consumida', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cantidad_liberada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionInventarioOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PREPARADA', 'Preparada'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada'), ('REVERSADA', 'Reversada')], default='PREPARADA', max_length=15)),
                ('clave_idempotencia', models.CharField(max_length=180, unique=True)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('reversado_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_neta', models.DecimalField(decimal_places=4, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='MermaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('motivo', models.CharField(max_length=255)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PARCIAL', 'Parcial'), ('CONSUMIDA', 'Consumida'), ('LIBERADA', 'Liberada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='loteinventario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loteinventario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loteinventario',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_inventario_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loteinventario',
            name='cantidad_reservada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='loteinventario',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('BLOQUEADO', 'Bloqueado'), ('VENCIDO', 'Vencido')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='loteinventario',
            name='fecha_fabricacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loteinventario',
            name='orden_produccion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_generados', to='inventario.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='loteinventario',
            name='referencia_origen',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='loteinventario',
            name='tipo_origen',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('COMPRA', 'Compra'), ('PRODUCCION', 'Produccion'), ('DEVOLUCION', 'Devolucion'), ('AJUSTE', 'Ajuste')], default='INICIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='loteinventario',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='aplicado_por_servicio',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='clave_idempotencia',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.loteinventario'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='inventario.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='revertido_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversiones', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='saldo_anterior',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='saldo_posterior',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='loteinventario',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='loteinventario',
            constraint=models.UniqueConstraint(fields=('empresa', 'producto', 'lote'), name='inv_lote_empresa_producto_numero_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loteinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_inicial__gte', 0)), name='inv_lote_inicial_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='loteinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_disponible__gte', 0)), name='inv_lote_disponible_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='loteinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_reservada__gte', 0)), name='inv_lote_reservada_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='loteinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_reservada__lte', models.F('cantidad_disponible'))), name='inv_lote_reserva_no_supera_disponible'),
        ),
        migrations.AddField(
            model_name='consumoproduccion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumoproduccion',
            name='movimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consumo', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='detallereservainventario',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.loteinventario'),
        ),
        migrations.AddField(
            model_name='detallereservainventario',
            name='necesidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.necesidadmateriaprima'),
        ),
        migrations.AddField(
            model_name='consumoproduccion',
            name='detalle_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.detallereservainventario'),
        ),
        migrations.AddField(
            model_name='devolucionproduccion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucionproduccion',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.loteinventario'),
        ),
        migrations.AddField(
            model_name='devolucionproduccion',
            name='movimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='devolucion_produccion', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='ejecucioninventarioorden',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ejecucioninventarioorden',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='ejecucioninventarioorden',
            name='iniciado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ejecucioninventarioorden',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ejecucion_inventario', to='inventario.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='ejecucioninventarioorden',
            name='reversado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucionproduccion',
            name='ejecucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventario.ejecucioninventarioorden'),
        ),
        migrations.AddField(
            model_name='consumoproduccion',
            name='ejecucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.ejecucioninventarioorden'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='ejecucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.ejecucioninventarioorden'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='ejecucion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lote_produccion', to='inventario.ejecucioninventarioorden'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='lote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='produccion', to='inventario.loteinventario'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='movimiento_entrada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lote_producido', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='mermaproduccion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mermaproduccion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mermaproduccion',
            name='ejecucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='inventario.ejecucioninventarioorden'),
        ),
        migrations.AddField(
            model_name='mermaproduccion',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.loteinventario'),
        ),
        migrations.AddField(
            model_name='mermaproduccion',
            name='movimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merma_produccion', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='reservainventario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservainventario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_inventario', to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='reservainventario',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_inventario', to='inventario.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='ejecucioninventarioorden',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='inventario.reservainventario'),
        ),
        migrations.AddField(
            model_name='detallereservainventario',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.reservainventario'),
        ),
        migrations.AddConstraint(
            model_name='reservainventario',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='inv_reserva_empresa_numero_uniq'),
        ),
        migrations.AddConstraint(
            model_name='detallereservainventario',
            constraint=models.UniqueConstraint(fields=('reserva', 'necesidad', 'lote'), name='inv_reserva_detalle_uniq'),
        ),
        migrations.AddConstraint(
            model_name='detallereservainventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_reservada__gt', 0)), name='inv_reserva_detalle_positiva'),
        ),
    ]
