# Generated by Django 6.0.4 on 2026-07-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_consumoproduccion_detallereservainventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('entrada_compra', 'Entrada por compra'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('produccion', 'Producción'), ('merma', 'Merma'), ('prestamo_entregado', 'Préstamo entregado'), ('prestamo_recibido', 'Préstamo recibido'), ('devolucion_prestamo', 'Devolución préstamo'), ('consumo_produccion', 'Consumo de produccion'), ('merma_produccion', 'Merma de produccion'), ('devolucion_produccion', 'Devolucion de produccion'), ('entrada_producto_terminado', 'Entrada de producto terminado'), ('reversion_consumo', 'Reversion de consumo'), ('reversion_entrada', 'Reversion de entrada')], max_length=30),
        ),
    ]
