# Generated by Django 6.0.4 on 2026-07-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_movimientoinventario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='es_reversion',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='naturaleza',
            field=models.CharField(blank=True, choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='operacion_origen',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
