# Generated by Django 6.0.4 on 2026-07-31 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_movimientoinventario_es_reversion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucioninventarioorden',
            options={'permissions': [('ejecutar_inventario_orden', 'Puede ejecutar inventario de una orden'), ('revertir_ejecucion_inventario', 'Puede revertir una ejecucion de inventario')]},
        ),
    ]
