# Generated by Django 6.0.4 on 2026-09-10 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0044_crear_plan_sastre_inabie'),
        ('inventario', '0013_alter_ejecucioninventarioorden_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenproduccion',
            options={'ordering': ['-fecha_programada', '-id'], 'permissions': [('programar_ordenproduccion', 'Puede programar órdenes de producción'), ('iniciar_ordenproduccion', 'Puede iniciar órdenes de producción'), ('completar_ordenproduccion', 'Puede completar órdenes de producción'), ('cancelar_ordenproduccion', 'Puede cancelar órdenes de producción'), ('ajustar_cantidad_ordenproduccion', 'Puede ajustar cantidad de producción'), ('autorizar_ordenproduccion', 'Puede autorizar ajustes de producción'), ('cambiar_producto_ordenproduccion', 'Puede cambiar excepcionalmente el producto'), ('cerrar_ordenproduccion', 'Puede cerrar producción')]},
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='autorizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_prod_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad_autorizada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad_sugerida',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_prod_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='iniciada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_prod_iniciadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='modalidad',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('PREPARA', 'PREPARA')], default='REGULAR', max_length=12),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='producto_planificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_planificadas', to='inventario.productoinventario'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='raciones_matricula',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='snapshot_produccion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AjusteOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CANTIDAD', 'Cantidad'), ('PRODUCTO', 'Producto')], max_length=12)),
                ('cantidad_original', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('cantidad_nueva', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('motivo', models.CharField(choices=[('MERMA_PREVISTA', 'Merma Prevista'), ('PRODUCCION_RESPALDO', 'Produccion Respaldo'), ('REPOSICION', 'Reposicion'), ('REDUCCION_RACIONES', 'Reduccion Raciones'), ('FALTANTE_MATERIA_PRIMA', 'Faltante Materia Prima'), ('AJUSTE_OPERATIVO', 'Ajuste Operativo'), ('REPROCESO', 'Reproceso'), ('OTRO', 'Otro')], max_length=32)),
                ('justificacion', models.TextField()),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_prod_autorizados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='inventario.ordenproduccion')),
                ('producto_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_producto_destino', to='inventario.productoinventario')),
                ('producto_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_producto_origen', to='inventario.productoinventario')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_prod_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_desviacion', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('cobertura_objetivo_dias', models.PositiveSmallIntegerField(default=15)),
                ('alerta_cobertura_dias', models.PositiveSmallIntegerField(default=3)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_produccion', to='conduces.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateField()),
                ('cobertura_dias', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fecha_agotamiento', models.DateField(blank=True, null=True)),
                ('cantidad_sugerida_compra', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('produccion_riesgo_fecha', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'materia_prima'), name='inv_alertaabast_empresa_materia_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ConsumoRealProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_teorica', models.DecimalField(decimal_places=4, max_digits=16)),
                ('cantidad_real', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('diferencia', models.DecimalField(decimal_places=4, max_digits=16)),
                ('porcentaje_desviacion', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('motivo', models.CharField(blank=True, choices=[('MERMA', 'Merma'), ('DERRAME', 'Derrame'), ('ERROR_PESADO', 'Error Pesado'), ('MATERIA_PRIMA_DEFECTUOSA', 'Materia Prima Defectuosa'), ('REPROCESO', 'Reproceso'), ('PRODUCCION_ADICIONAL', 'Produccion Adicional'), ('AJUSTE_TECNICO', 'Ajuste Tecnico'), ('OTRO', 'Otro')], max_length=32)),
                ('justificacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_reales', to='inventario.ordenproduccion')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('orden', 'materia_prima'), name='inv_consumoreal_orden_materia_uniq')],
            },
        ),
    ]
