# Generated by Django 6.0.4 on 2026-09-10 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0044_crear_plan_sastre_inabie'),
        ('inventario', '0014_alter_ordenproduccion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=32)),
                ('justificacion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('decidido_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_decision', models.TextField(blank=True)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_producto_decididos', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cambio_producto', to='inventario.ordenproduccion')),
                ('producto_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cambio_origen', to='inventario.productoinventario')),
                ('producto_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cambio_destino', to='inventario.productoinventario')),
                ('receta_solicitada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.recetaproduccion')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cambio_producto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('autorizar_cambio_producto', 'Puede autorizar o rechazar cambios de producto')],
            },
        ),
        migrations.CreateModel(
            name='MatriculaCentroVigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(default='INABIE', max_length=40)),
                ('modalidad', models.CharField(choices=[('REGULAR', 'Regular'), ('PREPARA', 'PREPARA')], default='REGULAR', max_length=12)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('raciones', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_vigentes', to='conduces.centroeducativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('centro', 'programa', 'modalidad', 'fecha_desde'), name='inv_matricula_centro_modalidad_desde_uniq')],
            },
        ),
        migrations.CreateModel(
            name='VinculoProductoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisado', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_producto', to='conduces.menudiario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'menu'), name='inv_vincmenu_empresa_menu_uniq')],
            },
        ),
    ]
