# Generated by Django 6.0.4 on 2026-09-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_solicitudcambioproducto_matriculacentrovigente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinventario',
            name='origen_catalogo',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('EXCEL', 'Excel'), ('RECETA', 'Receta')], default='MANUAL', max_length=12),
        ),
        migrations.AddField(
            model_name='productoinventario',
            name='requiere_revision',
            field=models.BooleanField(default=False),
        ),
    ]
