# Generated by Django 6.0.4 on 2026-09-20 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0046_centro_matriculas_por_dia'),
        ('inventario', '0016_recipe_catalog_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinventario',
            name='unidad_contenido_compra',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productoinventario',
            name='unidad_medida',
            field=models.CharField(choices=[('lb', 'Libras'), ('oz', 'Onzas'), ('ml', 'Mililitros'), ('fl_oz', 'Onzas líquidas'), ('gal_us', 'Galón estadounidense'), ('docena', 'Docena'), ('g', 'Gramos'), ('kg', 'Kilogramos'), ('unidad', 'Unidad'), ('galon', 'Galón'), ('litro', 'Litro'), ('paquete', 'Paquete'), ('caja', 'Caja'), ('yarda', 'Yarda')], default='lb', max_length=20),
        ),
        migrations.CreateModel(
            name='SecuenciaProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=4)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'prefijo'), name='inv_secuencia_producto_empresa_prefijo')],
            },
        ),
    ]
