# Generated by Django 6.0.4 on 2026-09-21 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0046_centro_matriculas_por_dia'),
        ('inventario', '0017_purchase_units_and_product_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasIngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_normalizado', models.CharField(max_length=180)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'alias_normalizado'), name='inv_alias_receta_empresa_nombre_uniq')],
            },
        ),
    ]
