# Generated by Django 6.0.4 on 2026-07-29 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conduces', '0026_dianodocencia'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=80)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('CAMBIAR_ESTADO', 'Cambiar estado'), ('CARGAR_DOCUMENTO', 'Cargar documento'), ('REEMPLAZAR_DOCUMENTO', 'Reemplazar documento'), ('ANULAR_DOCUMENTO', 'Anular documento'), ('DESCARGAR_DOCUMENTO', 'Descargar documento'), ('OTRO', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_auditoria', to='conduces.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['empresa', 'fecha'], name='aud_emp_fecha_idx'), models.Index(fields=['empresa', 'modulo'], name='aud_emp_modulo_idx'), models.Index(fields=['content_type', 'object_id'], name='aud_objeto_idx'), models.Index(fields=['usuario', 'fecha'], name='aud_usuario_fecha_idx')],
            },
        ),
    ]
