# Generated by Django 6.0.4 on 2026-07-30 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conduces', '0026_dianodocencia'),
        ('inventario', '0011_alter_movimientoinventario_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_movimientos', models.DecimalField(decimal_places=4, max_digits=16)),
                ('saldo_cacheado', models.DecimalField(decimal_places=4, max_digits=16)),
                ('saldo_lotes', models.DecimalField(decimal_places=4, max_digits=16)),
                ('diferencia_movimientos_cache', models.DecimalField(decimal_places=4, max_digits=16)),
                ('diferencia_lotes_cache', models.DecimalField(decimal_places=4, max_digits=16)),
                ('estado', models.CharField(choices=[('CONSISTENTE', 'Consistente'), ('DIFERENCIA', 'Diferencia'), ('CORREGIDA', 'Corregida'), ('IGNORADA', 'Ignorada')], max_length=15)),
                ('modo', models.CharField(choices=[('DIAGNOSTICO', 'Diagnostico'), ('CORRECCION', 'Correccion')], max_length=15)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
            ],
            options={
                'ordering': ['-fecha'],
                'permissions': [('run_inventory_diagnosis', 'Puede diagnosticar saldos de inventario'), ('rebuild_inventory_balance', 'Puede reconstruir saldos de inventario'), ('manage_document_sequences', 'Puede administrar secuencias documentales')],
            },
        ),
        migrations.CreateModel(
            name='EventoDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=120)),
                ('agregado_tipo', models.CharField(max_length=120)),
                ('agregado_id', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=180)),
                ('clave_idempotente', models.CharField(max_length=180)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.CharField(blank=True, max_length=500)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'permissions': [('retry_eventodominio', 'Puede reintentar eventos de dominio')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo_evento', 'clave_idempotente'), name='core_evento_empresa_tipo_clave_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RegistroIdempotencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=180)),
                ('operacion', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida')], default='INICIADA', max_length=15)),
                ('resultado_referencia', models.CharField(blank=True, max_length=250)),
                ('hash_solicitud', models.CharField(max_length=64)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'permissions': [('retry_registroidempotencia', 'Puede reintentar operaciones fallidas')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'operacion', 'clave'), name='core_idem_empresa_operacion_clave_uniq')],
            },
        ),
    ]
