# Generated by Django 6.0.4 on 2026-07-31 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0012_movimientoinventario_es_reversion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conciliacioninventario',
            options={'ordering': ['-fecha'], 'permissions': [('run_inventory_diagnosis', 'Puede diagnosticar saldos de inventario'), ('rebuild_inventory_balance', 'Puede reconstruir saldos de inventario'), ('manage_document_sequences', 'Puede administrar secuencias documentales'), ('view_transaction_engine', 'Puede ver el motor transaccional')]},
        ),
        migrations.AddField(
            model_name='conciliacioninventario',
            name='fecha_correccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conciliacioninventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.loteinventario'),
        ),
        migrations.AddField(
            model_name='conciliacioninventario',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conciliacioninventario',
            name='referencia',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='registroidempotencia',
            name='intentos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventodominio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15),
        ),
    ]
