# Generated by Django 6.0.4 on 2026-08-05 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('core', '0003_core2c_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('prioridad', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('url_origen', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('LEIDA', 'Leída'), ('POSPUESTA', 'Pospuesta'), ('RESUELTA', 'Resuelta')], default='NUEVA', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='FavoritoNavegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='pantalla', max_length=30)),
                ('etiqueta', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=500)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'usuario', 'url'), name='core_favorito_usuario_empresa_url_uniq')],
            },
        ),
        migrations.CreateModel(
            name='NavegacionReciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=40)),
                ('etiqueta', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=500)),
                ('visitado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visitado'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'usuario', 'url'), name='core_reciente_usuario_empresa_url_uniq')],
            },
        ),
    ]
