# Generated by Django 6.0.4 on 2026-08-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('conduces', '0029_empresa_modulo_inabie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=18)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas', to='catalogos.monedaempresa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'moneda', 'vigente_desde'), name='cat_tasa_emp_mon_fecha_uniq'), models.CheckConstraint(condition=models.Q(('tasa__gt', 0)), name='cat_tasa_cambio_positiva')],
            },
        ),
    ]
