# Generated by Django 6.0.4 on 2026-07-29 01:34

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conduces', '0026_dianodocencia'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_vencimiento', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='conduces.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to=documentos.models.ruta_documento)),
                ('nombre_original', models.CharField(editable=False, max_length=255)),
                ('extension', models.CharField(editable=False, max_length=10)),
                ('tamano_bytes', models.PositiveBigIntegerField(editable=False)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('confidencial', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('REEMPLAZADO', 'Reemplazado'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('object_id', models.PositiveBigIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documento_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazos', to='documentos.documento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='conduces.empresa')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.tipodocumento')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='tipodocumento',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='doc_tipo_empresa_codigo_uniq'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['empresa', 'estado'], name='doc_emp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['content_type', 'object_id'], name='doc_objeto_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['empresa', 'fecha_vencimiento'], name='doc_emp_venc_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['empresa', 'fecha_creacion'], name='doc_emp_creacion_idx'),
        ),
    ]
