# Generated by Django 6.0.4 on 2026-08-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaPrestamoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('pagada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNominaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=18)),
                ('deducciones', models.DecimalField(decimal_places=2, max_digits=18)),
                ('aportes', models.DecimalField(decimal_places=2, max_digits=18)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='EmbargoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('referencia', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaDetalleNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('snapshot', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('snapshot_reglas', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NovedadNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(default='APROBADA', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('estado', models.CharField(default='ABIERTO', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrestacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cuotas', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReciboNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('archivo', models.FileField(blank=True, upload_to='nomina/recibos/')),
            ],
        ),
        migrations.CreateModel(
            name='RegaliaPascual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anio', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReglaNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('condiciones', models.JSONField(default=dict)),
                ('formula', models.JSONField(default=dict)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('periodicidad', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('DEDUCCION', 'Deducción'), ('APORTE', 'Aporte')], max_length=12)),
                ('gravable', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
