# Generated by Django 6.0.4 on 2026-08-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('nomina', '0001_initial'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenominaempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='embargoempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='embargoempleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='lineadetallenomina',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.conceptonomina'),
        ),
        migrations.AddField(
            model_name='lineadetallenomina',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='nomina.detallenominaempleado'),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='historialnomina',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='nomina.nomina'),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.nomina'),
        ),
        migrations.AddField(
            model_name='novedadnomina',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.conceptonomina'),
        ),
        migrations.AddField(
            model_name='novedadnomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='novedadnomina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='periodonomina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='novedadnomina',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.periodonomina'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='nomina.periodonomina'),
        ),
        migrations.AddField(
            model_name='prestacionlaboral',
            name='liquidacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='nomina.liquidacionlaboral'),
        ),
        migrations.AddField(
            model_name='prestamoempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='prestamoempleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='cuotaprestamoempleado',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_detalle', to='nomina.prestamoempleado'),
        ),
        migrations.AddField(
            model_name='recibonomina',
            name='detalle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='nomina.detallenominaempleado'),
        ),
        migrations.AddField(
            model_name='regaliapascual',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='regaliapascual',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='reglanomina',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.conceptonomina'),
        ),
        migrations.AddField(
            model_name='reglanomina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='tiponomina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='periodonomina',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.tiponomina'),
        ),
    ]
