# Generated by Django 6.0.4 on 2026-08-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptonomina',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='recurrencia',
            field=models.CharField(default='PERIODO', max_length=20),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='vigente_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='vigente_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
