# Generated by Django 6.0.4 on 2026-08-21 02:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('nomina', '0003_conceptonomina_activo_conceptonomina_recurrencia_and_more'),
        ('rrhh', '0004_horaextra_aprobador_horaextra_horas_ordinarias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroLegalNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('sfs_empleado', models.DecimalField(decimal_places=6, max_digits=8)),
                ('afp_empleado', models.DecimalField(decimal_places=6, max_digits=8)),
                ('sfs_empleador', models.DecimalField(decimal_places=6, max_digits=8)),
                ('svds_empleador', models.DecimalField(decimal_places=6, max_digits=8)),
                ('srl_fijo', models.DecimalField(decimal_places=6, max_digits=8)),
                ('srl_variable', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('infotep_empleador', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('tope_sfs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tope_svds', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tope_srl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('escala_isr', models.JSONField(default=list)),
                ('fuentes', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-vigente_desde', '-version'),
            },
        ),
        migrations.CreateModel(
            name='PlantillaDocumentoRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('VOLANTE', 'Volante de pago'), ('NOMINA', 'Resumen de nómina'), ('PRESTACIONES', 'Cálculo de prestaciones'), ('LIQUIDACION', 'Carta de liquidación'), ('LABORAL', 'Carta laboral'), ('CONSULAR', 'Carta consular'), ('BANCARIA', 'Carta bancaria'), ('CONTRATO', 'Contrato'), ('ANEXO', 'Anexo de funciones')], max_length=20)),
                ('encabezado', models.TextField(blank=True)),
                ('firmante', models.CharField(blank=True, max_length=150)),
                ('cargo_firmante', models.CharField(blank=True, max_length=150)),
                ('pie', models.TextField(blank=True)),
                ('cuerpo', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='cotiza_infotep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='cotiza_tss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='origen',
            field=models.CharField(default='CONFIGURACION', max_length=30),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='afp_empleado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='alerta',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='horas_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='infotep_empleador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='isr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='otros_descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='otros_ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='salario_periodo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='sfs_empleado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='sfs_empleador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='srl_empleador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallenominaempleado',
            name='svds_empleador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='motivo_revision',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='requiere_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='salario_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='salario_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='tipo_terminacion',
            field=models.CharField(default='DESAHUCIO', max_length=30),
        ),
        migrations.AddField(
            model_name='nomina',
            name='total_afp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='nomina',
            name='total_aportes_patronales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='nomina',
            name='total_isr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='nomina',
            name='total_otros_descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='nomina',
            name='total_sfs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='prestacionlaboral',
            name='base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='prestacionlaboral',
            name='dias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='prestacionlaboral',
            name='formula',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='prestacionlaboral',
            name='referencia_legal',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recibonomina',
            name='generado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recibonomina',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='liquidacionlaboral',
            name='estado',
            field=models.CharField(default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='liquidacionlaboral',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='novedadnomina',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prestacionlaboral',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='detallenominaempleado',
            constraint=models.UniqueConstraint(fields=('nomina', 'empleado'), name='nomina_detalle_empleado_uniq'),
        ),
        migrations.AddField(
            model_name='parametrolegalnomina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='plantilladocumentorrhh',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddConstraint(
            model_name='parametrolegalnomina',
            constraint=models.UniqueConstraint(fields=('empresa', 'version'), name='nomina_param_legal_empresa_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='plantilladocumentorrhh',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo'), name='nomina_plantilla_tipo_uniq'),
        ),
    ]
