# Generated by Django 6.0.4 on 2026-08-21 22:39

import django.db.models.deletion
from django.db import migrations, models


def normalize_existing_loans(apps, schema_editor):
    Loan = apps.get_model('nomina', 'PrestamoEmpleado')
    counters = {}
    for loan in Loan.objects.order_by('empresa_id', 'pk'):
        counters[loan.empresa_id] = counters.get(loan.empresa_id, 0) + 1
        loan.codigo = f"PRE-LEGACY-{counters[loan.empresa_id]:06d}"
        loan.monto_cuota = loan.principal / loan.cuotas if loan.cuotas else loan.principal
        loan.estado = 'ACTIVO' if loan.saldo else 'PAGADO'
        loan.save(update_fields=['codigo', 'monto_cuota', 'estado'])


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('nomina', '0004_parametrolegalnomina_plantilladocumentorrhh_and_more'),
        ('rrhh', '0004_horaextra_aprobador_horaextra_horas_ordinarias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaprestamoempleado',
            name='estado',
            field=models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('APLICADA', 'Aplicada'), ('REVERSADA', 'Reversada')], default='PROVISIONAL', max_length=15),
        ),
        migrations.AddField(
            model_name='cuotaprestamoempleado',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuotaprestamoempleado',
            name='nomina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas_prestamos', to='nomina.nomina'),
        ),
        migrations.AddField(
            model_name='cuotaprestamoempleado',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cuotaprestamoempleado',
            name='saldo_posterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='prestamoempleado',
            name='codigo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='prestamoempleado',
            name='documento_soporte',
            field=models.FileField(blank=True, upload_to='nomina/prestamos/'),
        ),
        migrations.AddField(
            model_name='prestamoempleado',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('PAGADO', 'Pagado'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=15),
        ),
        migrations.AddField(
            model_name='prestamoempleado',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamoempleado',
            name='monto_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='prestamoempleado',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prestamoempleado',
            name='primera_nomina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomina.periodonomina'),
        ),
        migrations.AddField(
            model_name='prestamoempleado',
            name='tipo',
            field=models.CharField(choices=[('PRESTAMO', 'Préstamo'), ('ADELANTO', 'Adelanto'), ('UNICO', 'Descuento único'), ('RECURRENTE', 'Descuento recurrente'), ('OTRO', 'Otro')], default='PRESTAMO', max_length=15),
        ),
        migrations.AlterField(
            model_name='prestamoempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_descuentos', to='rrhh.empleado'),
        ),
        migrations.RunPython(normalize_existing_loans, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cuotaprestamoempleado',
            constraint=models.UniqueConstraint(condition=models.Q(('nomina__isnull', False)), fields=('prestamo', 'nomina'), name='nomina_cuota_prestamo_nomina_uniq'),
        ),
        migrations.AddConstraint(
            model_name='prestamoempleado',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='nomina_prestamo_empresa_codigo_uniq'),
        ),
    ]
