# Generated by Django 6.0.4 on 2026-08-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('contabilidad', '0006_anticipoproveedor_cuentacontable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscenarioPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BASE', 'Base'), ('OPTIMISTA', 'Optimista'), ('PESIMISTA', 'Pesimista')], max_length=12)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LineaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensiones', models.JSONField(default=dict)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='presupuesto.escenariopresupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha', models.DateField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.asientocontable')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='presupuesto.lineapresupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='DistribucionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='presupuesto.lineapresupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='CompromisoPresupuestario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=80)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(default='ACTIVO', max_length=15)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='presupuesto.lineapresupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('anio', models.PositiveIntegerField()),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('periodicidad', models.CharField(default='MENSUAL', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='presupuesto.presupuesto')),
            ],
        ),
        migrations.AddField(
            model_name='escenariopresupuesto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='presupuesto.presupuesto'),
        ),
        migrations.CreateModel(
            name='VersionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='presupuesto.presupuesto')),
            ],
        ),
    ]
