from core.domain.events import DomainEvent
class ClienteActualizado(DomainEvent):pass
class ClienteActivado(DomainEvent):pass
class ClienteSuspendido(DomainEvent):pass
class ClienteBloqueadoCredito(DomainEvent):pass
class ClienteDesbloqueadoCredito(DomainEvent):pass
class LimiteCreditoActualizado(DomainEvent):pass
class RiesgoClienteActualizado(DomainEvent):pass
class ProductoComercialCreado(DomainEvent):pass
class ListaPrecioCreada(DomainEvent):pass
class ListaPrecioActivada(DomainEvent):pass
class ListaPrecioVersionada(DomainEvent):pass
class PrecioResuelto(DomainEvent):pass
class DescuentoAplicado(DomainEvent):pass
class PromocionAplicada(DomainEvent):pass
class PrecioExcepcionalSolicitado(DomainEvent):pass
class CotizacionCreada(DomainEvent):pass
class CotizacionActualizada(DomainEvent):pass
class CotizacionVersionada(DomainEvent):pass
class CotizacionEnviadaRevision(DomainEvent):pass
class CotizacionAprobada(DomainEvent):pass
class CotizacionEnviada(DomainEvent):pass
class CotizacionAceptada(DomainEvent):pass
class CotizacionRechazada(DomainEvent):pass
class CotizacionVencida(DomainEvent):pass
class CotizacionCancelada(DomainEvent):pass
class CotizacionConvertida(DomainEvent):pass
class PedidoCreado(DomainEvent):pass
class PedidoCreadoDesdeCotizacion(DomainEvent):pass
class PedidoAprobado(DomainEvent):pass
class PedidoRechazado(DomainEvent):pass
class PedidoReabierto(DomainEvent):pass
class PedidoCancelado(DomainEvent):pass
class PedidoProgramado(DomainEvent):pass
class PedidoReprogramado(DomainEvent):pass
class DemandaComercialPublicada(DomainEvent):pass
class DocumentoComercialActualizado(DomainEvent):pass
class ExportacionComercialGenerada(DomainEvent):pass
