from core.domain.events import DomainEvent

_NAMES="""ReservaComercialCreada ReservaComercialCompletada ReservaComercialLiberada ReservaComercialExpirada ReservaComercialCancelada PreparacionCreada PreparacionIniciada PreparacionValidada PickingCreado PickingAsignado PickingCompletado PickingValidado PackingCreado PackingSellado DespachoCreado DespachoAutorizado DespachoEnRuta DespachoCompletado ConduceComercialCreado ConduceComercialEmitido ConduceComercialAnulado EntregaCreada EntregaEnSitio EntregaConfirmada EntregaRechazada IncidenciaEntregaCreada FacturaVentaCreada FacturaVentaEmitida FacturaVentaAnulada FacturaVentaContabilizada NotaCreditoEmitida NotaCreditoVentaContabilizada NotaDebitoEmitida NotaDebitoVentaContabilizada CuentaPorCobrarCreada CuentaPorCobrarActualizada CobroRegistrado CobroAplicado CobroContabilizado CobroRevertido FacturaCedidaFactoring CesionFactoringSolicitada CesionFactoringAprobada CesionFactoringCedida CesionFactoringPagada DocumentoO2CActualizado ExportacionO2CGenerada""".split()
globals().update({name:type(name,(DomainEvent,),{}) for name in _NAMES})
__all__=_NAMES
for _extra in "FactoringSolicitado FactoringAprobado DesembolsoFactoringRegistrado FactoringContabilizado FactoringCancelado FactoringReversado CobroReversionSolicitada AplicacionCobroRevertida SaldoCxCActualizado ExportacionO2CFinancieraGenerada".split():
    globals()[_extra]=type(_extra,(DomainEvent,),{})
    __all__.append(_extra)
