from core.domain.events import DomainEvent

_NAMES="""ReservaComercialCreada ReservaComercialCompletada ReservaComercialLiberada ReservaComercialExpirada ReservaComercialCancelada PreparacionCreada PreparacionIniciada PreparacionValidada PickingCreado PickingAsignado PickingCompletado PickingValidado PackingCreado PackingSellado DespachoCreado DespachoAutorizado DespachoEnRuta DespachoCompletado ConduceComercialCreado ConduceComercialEmitido ConduceComercialAnulado EntregaCreada EntregaEnSitio EntregaConfirmada EntregaRechazada IncidenciaEntregaCreada FacturaVentaCreada FacturaVentaEmitida FacturaVentaAnulada NotaCreditoEmitida NotaDebitoEmitida CuentaPorCobrarCreada CuentaPorCobrarActualizada CobroRegistrado CobroAplicado CobroRevertido CesionFactoringSolicitada CesionFactoringAprobada CesionFactoringCedida CesionFactoringPagada DocumentoO2CActualizado ExportacionO2CGenerada""".split()
globals().update({name:type(name,(DomainEvent,),{}) for name in _NAMES})
__all__=_NAMES
