# Generated by Django 6.0.4 on 2026-04-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('matricula', models.IntegerField()),
            ],
        ),
    ]
