# Generated by Django 6.0.4 on 2026-04-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0002_conduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduce',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
