# Generated by Django 6.0.4 on 2026-04-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0003_conduce_confirmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conduce',
            name='confirmado',
        ),
        migrations.AddField(
            model_name='conduce',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('emitido', 'Emitido'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
    ]
