# Generated by Django 6.0.4 on 2026-04-24 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0004_remove_conduce_confirmado_conduce_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rnc', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('representante', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='conduce',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
            preserve_default=False,
        ),
    ]
