# Generated by Django 6.0.4 on 2026-04-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0005_empresa_conduce_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroeducativo',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centroeducativo',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centroeducativo',
            name='regional_distrito',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='centroeducativo',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conduce',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
