# Generated by Django 6.0.4 on 2026-04-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0006_centroeducativo_direccion_centroeducativo_provincia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='representante',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rnc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
