# Generated by Django 6.0.4 on 2026-04-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0007_remove_empresa_representante_empresa_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduce',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
