# Generated by Django 6.0.4 on 2026-04-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0008_alter_conduce_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(max_length=100)),
            ],
        ),
    ]
