# Generated by Django 6.0.4 on 2026-04-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0009_menudiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='numero_inicial_conduce',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='matricula',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='regional_distrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conduce',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conduce',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('entregado', 'Entregado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='conduce',
            name='numero',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conduce',
            name='producto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rnc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menudiario',
            name='fecha',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='menudiario',
            name='producto',
            field=models.CharField(max_length=255),
        ),
    ]
