# Generated by Django 6.0.4 on 2026-04-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0010_empresa_numero_inicial_conduce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduce',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_inicial_conduce',
            field=models.CharField(default='0001', max_length=20),
        ),
    ]
