# Generated by Django 6.0.4 on 2026-04-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0011_alter_conduce_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduce',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('entregado', 'Entregado'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
    ]
