# Generated by Django 6.0.4 on 2026-04-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0012_alter_conduce_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroeducativo',
            name='orden_carga',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
