# Generated by Django 6.0.4 on 2026-05-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0013_centroeducativo_orden_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduce',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='conduce',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
