# Generated by Django 6.0.4 on 2026-05-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0014_conduce_latitud_conduce_longitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centroeducativo',
            options={'ordering': ['orden_carga', 'id']},
        ),
        migrations.AlterModelOptions(
            name='conduce',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='menudiario',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='conduce',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='conduce',
            name='longitud',
        ),
        migrations.AddField(
            model_name='centroeducativo',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='centroeducativo',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
