# Generated by Django 6.0.4 on 2026-05-02 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0015_alter_centroeducativo_options_alter_conduce_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncf', models.CharField(max_length=20, unique=True)),
                ('fecha_validez', models.DateField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ncf'],
            },
        ),
        migrations.CreateModel(
            name='ProductoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PAN', 'Pan'), ('PAN_CON_VEGETALES', 'Pan con vegetales'), ('GALLETA', 'Galleta'), ('BIZCOCHO', 'Bizcocho')], max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_sin_itbis', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aplica_itbis', models.BooleanField(default=True)),
                ('porcentaje_itbis', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(default='INSTITUTO NACIONAL DE BIENESTAR ESTUDIANTIL', max_length=255)),
                ('cliente_rnc', models.CharField(default='401-50561-4', max_length=20)),
                ('fecha_factura', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_conduces', models.IntegerField(default=0)),
                ('conduce_inicial', models.CharField(blank=True, max_length=20, null=True)),
                ('conduce_final', models.CharField(blank=True, max_length=20, null=True)),
                ('bloques', models.PositiveIntegerField(default=1)),
                ('subtotal_exento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('itbis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conduces.comprobantefiscal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'ordering': ['-fecha_factura', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_sin_itbis', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aplica_itbis', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='conduces.factura')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
