# Generated by Django 6.0.4 on 2026-05-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0016_comprobantefiscal_productofacturacion_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoComprobanteGubernamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(default='B15', max_length=3)),
                ('numero_desde', models.PositiveIntegerField()),
                ('numero_hasta', models.PositiveIntegerField()),
                ('fecha_validez', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rango de comprobantes gubernamentales',
                'verbose_name_plural': 'Rangos de comprobantes gubernamentales',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='comprobantefiscal',
            options={'ordering': ['ncf'], 'verbose_name': 'Comprobante gubernamental', 'verbose_name_plural': 'Comprobantes gubernamentales'},
        ),
        migrations.RenameField(
            model_name='productofacturacion',
            old_name='nombre',
            new_name='nombre_factura',
        ),
        migrations.AddField(
            model_name='comprobantefiscal',
            name='tipo',
            field=models.CharField(choices=[('GUBERNAMENTAL', 'Factura gubernamental')], default='GUBERNAMENTAL', max_length=30),
        ),
        migrations.AddField(
            model_name='factura',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productofacturacion',
            name='categoria',
            field=models.CharField(choices=[('PAN', 'PAN'), ('PAN_CON_VEGETALES', 'PAN CON VEGETALES'), ('GALLETA', 'GALLETA'), ('BIZCOCHO', 'BIZCOCHO')], max_length=50, unique=True),
        ),
    ]
