# Generated by Django 6.0.4 on 2026-05-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0017_rangocomprobantegubernamental_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='actualizada_en',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='creada_en',
        ),
        migrations.AlterField(
            model_name='comprobantefiscal',
            name='tipo',
            field=models.CharField(choices=[('B01', 'B01 - Crédito fiscal'), ('B02', 'B02 - Consumo'), ('B14', 'B14 - Régimen especial'), ('B15', 'B15 - Gubernamental'), ('E31', 'E31 - e-CF crédito fiscal'), ('E32', 'E32 - e-CF consumo'), ('E44', 'E44 - e-CF gubernamental'), ('OTRO', 'Otro')], default='GUBERNAMENTAL', max_length=30),
        ),
    ]
