# Generated by Django 6.0.4 on 2026-05-03 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0018_alter_factura_options_remove_factura_actualizada_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobantefiscal',
            options={'ordering': ['ncf'], 'verbose_name': 'Comprobante / NCF', 'verbose_name_plural': 'Comprobantes / NCF'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha_factura', '-id']},
        ),
        migrations.AlterModelOptions(
            name='rangocomprobantegubernamental',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Rango de comprobantes', 'verbose_name_plural': 'Rangos de comprobantes'},
        ),
        migrations.AddField(
            model_name='factura',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='codigo_seguridad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='encf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='es_electronica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado_dgii',
            field=models.CharField(blank=True, default='pendiente', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_firma_digital',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='pdf_ecf_externo',
            field=models.FileField(blank=True, null=True, upload_to='facturas/pdf_externo/'),
        ),
        migrations.AddField(
            model_name='factura',
            name='url_qr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='xml_ecf',
            field=models.FileField(blank=True, null=True, upload_to='facturas/xml/'),
        ),
        migrations.AlterField(
            model_name='comprobantefiscal',
            name='ncf',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='comprobantefiscal',
            name='tipo',
            field=models.CharField(choices=[('B01', 'B01 - Crédito fiscal'), ('B02', 'B02 - Consumo'), ('B14', 'B14 - Régimen especial'), ('B15', 'B15 - Gubernamental'), ('E31', 'E31 - e-CF crédito fiscal'), ('E32', 'E32 - e-CF consumo'), ('E44', 'E44 - e-CF gubernamental'), ('OTRO', 'Otro')], default='B15', max_length=30),
        ),
        migrations.AlterField(
            model_name='rangocomprobantegubernamental',
            name='prefijo',
            field=models.CharField(default='B15', max_length=5),
        ),
    ]
