# Generated by Django 6.0.4 on 2026-05-04 05:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0019_alter_comprobantefiscal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rnc', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_conduces', models.IntegerField(default=500)),
                ('limite_usuarios', models.IntegerField(default=3)),
                ('almacenamiento_gb', models.IntegerField(default=1)),
                ('incluye_contabilidad', models.BooleanField(default=False)),
                ('incluye_nomina', models.BooleanField(default=False)),
                ('incluye_rutas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('prueba', 'Prueba'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('bloqueada', 'Bloqueada')], default='prueba', max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField()),
                ('en_prueba', models.BooleanField(default=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresasaas')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conduces.plan')),
            ],
        ),
    ]
