# Generated by Django 6.0.4 on 2026-05-05 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0022_empresa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroeducativo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='comprobantefiscal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_centros',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_conduces',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_facturacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_nomina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_reportes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_rutas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menudiario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='productofacturacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comprobantefiscal',
            name='ncf',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menudiario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productofacturacion',
            name='categoria',
            field=models.CharField(choices=[('PAN', 'PAN'), ('PAN_CON_VEGETALES', 'PAN CON VEGETALES'), ('GALLETA', 'GALLETA'), ('BIZCOCHO', 'BIZCOCHO')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='comprobantefiscal',
            unique_together={('empresa', 'ncf')},
        ),
        migrations.AlterUniqueTogether(
            name='productofacturacion',
            unique_together={('empresa', 'categoria')},
        ),
    ]
