# Generated by Django 6.0.4 on 2026-05-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0023_centroeducativo_empresa_comprobantefiscal_empresa_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menudiario',
            unique_together={('empresa', 'fecha')},
        ),
    ]
