# Generated by Django 6.0.4 on 2026-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0024_alter_menudiario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/'),
        ),
    ]
