# Generated by Django 6.0.4 on 2026-05-14 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0025_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNoDocencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado'), ('no_docencia', 'No docencia'), ('suspension', 'Suspensión de clases'), ('otro', 'Otro')], default='feriado', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'verbose_name': 'Día no docencia',
                'verbose_name_plural': 'Días no docencia',
                'ordering': ['fecha'],
                'unique_together': {('empresa', 'fecha', 'motivo')},
            },
        ),
    ]
