# Generated by Django 6.0.4 on 2026-07-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0026_dianodocencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modulo_catalogos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_compras',
            field=models.BooleanField(default=False),
        ),
    ]
