# Generated by Django 6.0.4 on 2026-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0027_empresa_modulo_catalogos_empresa_modulo_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modulo_workflow',
            field=models.BooleanField(default=False),
        ),
    ]
