# Generated by Django 6.0.4 on 2026-08-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0028_empresa_modulo_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modulo_inabie',
            field=models.BooleanField(default=False),
        ),
    ]
