# Generated by Django 6.0.4 on 2026-08-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigovalidacion',
            name='intentos_fallidos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
