# Generated by Django 6.0.4 on 2026-08-31 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0031_conduce_eliminado_en_conduce_eliminado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCicloMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveSmallIntegerField()),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='0=Lunes, 6=Domingo')),
                ('producto', models.CharField(blank=True, max_length=180)),
                ('es_suministrado', models.BooleanField(default=True, help_text='Desmarcar para bebidas u otros componentes no suministrados.')),
                ('observacion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('semana', 'dia_semana'),
            },
        ),
        migrations.CreateModel(
            name='AsignacionProgramaCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('REGULAR', 'Regular'), ('PREPARA', 'PREPARA'), ('OTRA', 'Otra')], max_length=20)),
                ('dias_entrega', models.JSONField(default=list, help_text='Dias Python: lunes=0, domingo=6')),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_menu', to='conduces.centroeducativo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('centro_id', '-vigente_desde'),
            },
        ),
        migrations.CreateModel(
            name='CalendarioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('anio_inicio', models.PositiveSmallIntegerField()),
                ('anio_fin', models.PositiveSmallIntegerField()),
                ('inicio_docencia', models.DateField()),
                ('fin_docencia', models.DateField()),
                ('dias_docencia_oficiales', models.PositiveSmallIntegerField(default=190)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20)),
                ('documento_fuente', models.FileField(blank=True, null=True, upload_to='calendarios_escolares/')),
                ('diferencia_justificada', models.TextField(blank=True)),
                ('activado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendarios_activados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_escolares', to='conduces.empresa')),
            ],
            options={
                'ordering': ('-anio_inicio', 'empresa_id'),
                'permissions': [('activar_calendario_escolar', 'Puede activar calendario escolar')],
            },
        ),
        migrations.CreateModel(
            name='DiaCalendarioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('clasificacion', models.CharField(choices=[('DOCENCIA', 'Docencia'), ('FERIADO', 'Feriado'), ('VACACIONES', 'Vacaciones'), ('NO_LECTIVO', 'No lectivo'), ('SUSPENSION', 'Suspension'), ('REQUIERE_REVISION', 'Requiere revision')], default='REQUIERE_REVISION', max_length=25)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('origen', models.CharField(default='MANUAL', max_length=30)),
                ('ajustado_en', models.DateTimeField(auto_now=True)),
                ('ajustado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_calendario_ajustados', to=settings.AUTH_USER_MODEL)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='conduces.calendarioescolar')),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='ProgramacionMenuEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia_semana', models.PositiveSmallIntegerField()),
                ('semana_ciclo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('producto', models.CharField(blank=True, max_length=180)),
                ('programa_snapshot', models.CharField(max_length=160)),
                ('version_snapshot', models.CharField(max_length=80)),
                ('modalidad_snapshot', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('SIN_DOCENCIA', 'Sin docencia'), ('NO_PROGRAMADO', 'No programado'), ('NO_SUMINISTRADO', 'Componente no suministrado'), ('OMITIDO', 'Omitido por excepcion'), ('EXTRAORDINARIO', 'Entrega extraordinaria')], max_length=20)),
                ('confirmada', models.BooleanField(default=False)),
                ('bloqueada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='conduces.asignacionprogramacentro')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='conduces.calendarioescolar')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_menu', to='conduces.centroeducativo')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_menu_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_menu', to='conduces.empresa')),
                ('item_ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conduces.itemciclomenu')),
            ],
            options={
                'ordering': ('fecha', 'centro_id'),
                'permissions': [('confirmar_programacion_menu', 'Puede confirmar programacion de menu')],
            },
        ),
        migrations.CreateModel(
            name='ExcepcionProgramacionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('SIN_DOCENCIA', 'Sin docencia'), ('NO_PROGRAMADO', 'No programado'), ('NO_SUMINISTRADO', 'Componente no suministrado'), ('OMITIDO', 'Omitido por excepcion'), ('EXTRAORDINARIO', 'Entrega extraordinaria')], max_length=20)),
                ('producto_anterior', models.CharField(blank=True, max_length=180)),
                ('producto_nuevo', models.CharField(blank=True, max_length=180)),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excepciones', to='conduces.programacionmenuescolar')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='ProgramaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=160)),
                ('modalidad', models.CharField(choices=[('REGULAR', 'Regular'), ('PREPARA', 'PREPARA'), ('OTRA', 'Otra')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_menu', to='conduces.empresa')),
            ],
            options={
                'ordering': ('modalidad', 'nombre'),
            },
        ),
        migrations.AddField(
            model_name='programacionmenuescolar',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conduces.programamenu'),
        ),
        migrations.AddField(
            model_name='asignacionprogramacentro',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_centros', to='conduces.programamenu'),
        ),
        migrations.CreateModel(
            name='VersionProgramaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('semanas_ciclo', models.PositiveSmallIntegerField(default=5)),
                ('fecha_ancla_ciclo', models.DateField()),
                ('modo_inicio_ciclo', models.CharField(choices=[('CONTINUAR', 'Continuar ciclo existente'), ('REINICIAR', 'Reiniciar en semana 1'), ('ESPECIFICA', 'Iniciar en semana especifica')], default='REINICIAR', max_length=15)),
                ('semana_inicial', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=15)),
                ('documento_fuente', models.FileField(blank=True, null=True, upload_to='programas_menu/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_menu_creadas', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='conduces.programamenu')),
            ],
            options={
                'ordering': ('programa_id', '-vigente_desde'),
            },
        ),
        migrations.AddField(
            model_name='programacionmenuescolar',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conduces.versionprogramamenu'),
        ),
        migrations.AddField(
            model_name='itemciclomenu',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='conduces.versionprogramamenu'),
        ),
        migrations.AddConstraint(
            model_name='calendarioescolar',
            constraint=models.UniqueConstraint(fields=('empresa', 'anio_inicio', 'anio_fin'), name='cal_escolar_empresa_anio_uniq'),
        ),
        migrations.AddConstraint(
            model_name='diacalendarioescolar',
            constraint=models.UniqueConstraint(fields=('calendario', 'fecha'), name='dia_calendario_fecha_uniq'),
        ),
        migrations.AddConstraint(
            model_name='programamenu',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='programa_menu_empresa_codigo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='versionprogramamenu',
            constraint=models.UniqueConstraint(fields=('programa', 'nombre'), name='version_programa_nombre_uniq'),
        ),
        migrations.AddConstraint(
            model_name='programacionmenuescolar',
            constraint=models.UniqueConstraint(fields=('asignacion', 'fecha'), name='programacion_asignacion_fecha_uniq'),
        ),
        migrations.AddConstraint(
            model_name='itemciclomenu',
            constraint=models.UniqueConstraint(fields=('version', 'semana', 'dia_semana'), name='item_ciclo_semana_dia_uniq'),
        ),
    ]
