# Generated by Django 6.0.4 on 2026-08-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0032_itemciclomenu_asignacionprogramacentro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaOficialCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_inicio', models.PositiveSmallIntegerField()),
                ('anio_fin', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField()),
                ('clasificacion', models.CharField(choices=[('DOCENCIA', 'Docencia'), ('FERIADO', 'Feriado'), ('VACACIONES', 'Vacaciones'), ('NO_LECTIVO', 'No lectivo'), ('SUSPENSION', 'Suspension'), ('REQUIERE_REVISION', 'Requiere revision')], max_length=25)),
                ('motivo', models.CharField(max_length=255)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('anio_inicio', 'fecha'),
                'constraints': [models.UniqueConstraint(fields=('anio_inicio', 'anio_fin', 'fecha'), name='fecha_oficial_calendario_uniq')],
            },
        ),
    ]
