# Generated by Django 6.0.4 on 2026-09-01 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0034_fecha_oficial_adp_2026_2027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarioescolar',
            name='dias_docencia_oficiales',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnalisisDocumentoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='calendarios_escolares/analisis/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('hash_sha256', models.CharField(db_index=True, max_length=64)),
                ('proveedor', models.CharField(max_length=80)),
                ('version_proveedor', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('PROCESANDO', 'Procesando'), ('DETECTADO', 'Detectado'), ('REQUIERE_REVISION', 'Requiere revision'), ('CONFIRMADO', 'Confirmado'), ('FALLIDO', 'Fallido')], default='PROCESANDO', max_length=25)),
                ('confianza', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('datos_detectados', models.JSONField(default=dict)),
                ('advertencias', models.JSONField(default=list)),
                ('texto_extraido', models.TextField(blank=True)),
                ('paginas', models.PositiveSmallIntegerField(default=0)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('calendario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analisis_documentales', to='conduces.calendarioescolar')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_calendario_confirmados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analisis_calendario_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_calendario', to='conduces.empresa')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='EventoDocumentoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('clasificacion', models.CharField(choices=[('DOCENCIA', 'Docencia'), ('FERIADO', 'Feriado'), ('VACACIONES', 'Vacaciones'), ('NO_LECTIVO', 'No lectivo'), ('SUSPENSION', 'Suspension'), ('REQUIERE_REVISION', 'Requiere revision')], max_length=25)),
                ('tipo_contextual', models.CharField(default='OTRO', max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('evidencia', models.TextField(blank=True)),
                ('pagina', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confianza', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('DETECTADO', 'Detectado'), ('CONFIRMADO', 'Confirmado'), ('REQUIERE_REVISION', 'Requiere revision'), ('CORREGIDO', 'Corregido')], default='DETECTADO', max_length=25)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='conduces.analisisdocumentocalendario')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('fecha_inicio', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TotalMensualCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('dias_declarados', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dias_calculados', models.PositiveSmallIntegerField(default=0)),
                ('diferencia', models.SmallIntegerField(default=0)),
                ('estado', models.CharField(default='REQUIERE_REVISION', max_length=25)),
                ('evidencia', models.TextField(blank=True)),
                ('pagina', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('explicacion', models.TextField(blank=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totales_mensuales', to='conduces.analisisdocumentocalendario')),
            ],
            options={
                'ordering': ('anio', 'mes'),
                'constraints': [models.UniqueConstraint(fields=('analisis', 'anio', 'mes'), name='total_mensual_analisis_uniq')],
            },
        ),
    ]
