# Generated by Django 6.0.4 on 2026-09-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0035_alter_calendarioescolar_dias_docencia_oficiales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionprogramamenu',
            name='fecha_uso_desde',
            field=models.DateField(blank=True, help_text='Fecha desde la cual esta versión comienza a utilizarse operativamente en SASTRE.', null=True),
        ),
    ]
