# Generated by Django 6.0.4 on 2026-09-04 01:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0036_versionprogramamenu_fecha_uso_desde'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=30)),
                ('tipo', models.CharField(choices=[('NOTA_ACLARATORIA', 'Nota aclaratoria'), ('CARTA_REMISION', 'Carta de remision'), ('CERTIFICACION', 'Certificacion'), ('COMUNICACION_INABIE', 'Comunicacion INABIE'), ('COMUNICACION_PROVEEDOR', 'Comunicacion a proveedor'), ('OTRO', 'Otro')], db_index=True, default='NOTA_ACLARATORIA', max_length=40)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], db_index=True, default='BORRADOR', max_length=20)),
                ('origen', models.CharField(choices=[('AUTOMATICO', 'Generado por SASTRE'), ('MANUAL', 'Redaccion manual'), ('ASISTIDO', 'Redaccion asistida')], default='AUTOMATICO', max_length=20)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_desde', models.DateField(blank=True, db_index=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, db_index=True, null=True)),
                ('destinatario', models.CharField(blank=True, max_length=255)),
                ('asunto', models.CharField(blank=True, max_length=255)),
                ('contenido_html', models.TextField(blank=True)),
                ('firmante', models.CharField(blank=True, max_length=180)),
                ('cargo_firmante', models.CharField(blank=True, max_length=180)),
                ('incluir_firma', models.BooleanField(default=False)),
                ('incluir_sello', models.BooleanField(default=False)),
                ('dias_no_laborables_snapshot', models.JSONField(blank=True, default=list)),
                ('datos_snapshot', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_institucionales_creados', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_institucionales_eliminados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_institucionales', to='conduces.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_institucionales_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_documento', '-id'),
                'indexes': [models.Index(fields=['empresa', 'tipo', 'estado'], name='doc_empresa_tipo_estado_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'numero'), name='documento_empresa_numero_uniq')],
            },
        ),
    ]
