# Generated by Django 6.0.4 on 2026-09-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0037_documentoinstitucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='firma_autorizada',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/firmas/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sello_institucional',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/sellos/'),
        ),
    ]
