# Generated by Django 6.0.4 on 2026-09-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0038_empresa_firma_autorizada_empresa_sello_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cargo_firmante_predeterminado',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='firmante_predeterminado',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
