# Generated by Django 6.0.4 on 2026-09-05 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0039_empresa_cargo_firmante_predeterminado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoinstitucional',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoinstitucional',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_institucionales_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoinstitucional',
            name='finalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_institucionales_finalizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoinstitucional',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentoinstitucional',
            name='pdf_final',
            field=models.FileField(blank=True, null=True, upload_to='documentos_institucionales/finalizados/%Y/%m/'),
        ),
    ]
