# Generated by Django 6.0.4 on 2026-09-05 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0040_documentoinstitucional_anulado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoinstitucional',
            name='documento_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versiones_derivadas', to='conduces.documentoinstitucional'),
        ),
        migrations.AddField(
            model_name='documentoinstitucional',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
