# Generated by Django 6.0.4 on 2026-09-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0041_documentoinstitucional_documento_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoinstitucional',
            name='docx_final',
            field=models.FileField(blank=True, null=True, upload_to='documentos_institucionales/finalizados/%Y/%m/'),
        ),
    ]
