# Generated by Django 6.0.4 on 2026-09-07 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0042_documentoinstitucional_docx_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasaas',
            name='fecha_suspension',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresasaas',
            name='motivo_suspension',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresasaas',
            name='requiere_pago',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresasaas',
            name='suspendida_manualmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresasaas',
            name='trial_dias',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='plan',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_catalogos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_centros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_compras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_conduces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_facturacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_inabie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_nomina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_reportes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_rutas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='modulo_workflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='moneda',
            field=models.CharField(default='DOP', max_length=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='periodicidad',
            field=models.CharField(choices=[('MONTHLY', 'Mensual')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='cancelada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='cancelar_al_final_periodo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_proximo_cobro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='gracia_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='periodo_actual_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='periodo_actual_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='proveedor',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PAYPAL', 'PayPal'), ('TRANSFERENCIA', 'Transferencia'), ('CORTESIA', 'Cortesía')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='proveedor_subscription_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='ultimo_pago_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='conduces.empresasaas'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('pendiente_pago', 'Pendiente de pago'), ('activa', 'Activa'), ('pago_fallido', 'Pago fallido'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('bloqueada', 'Bloqueada')], default='prueba', max_length=20),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conduces.plan'),
        ),
        migrations.CreateModel(
            name='EventoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_suscripcion', to='conduces.empresasaas')),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='conduces.suscripcion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(default='MANUAL', max_length=20)),
                ('referencia_externa', models.CharField(blank=True, max_length=180, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='DOP', max_length=3)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('periodo_desde', models.DateField(blank=True, null=True)),
                ('periodo_hasta', models.DateField(blank=True, null=True)),
                ('datos_referencia', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_suscripcion', to='conduces.empresasaas')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='conduces.suscripcion')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
