# Generated by Django 6.0.4 on 2026-09-16 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0044_crear_plan_sastre_inabie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduce',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='conduce',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='conduce_empresa_numero_uniq'),
        ),
    ]
