"""
Django settings for panaderia_saas project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-6=wwu*%g!tf&!b7x6_v4w%6e9hn9n@8lvhsdjf$ku#$n5$+m(%"
)

DEBUG = os.environ.get("DEBUG", "True") == "True"
SEDL_CATALOG_ENABLED = os.environ.get("SEDL_CATALOG_ENABLED", str(DEBUG)) == "True"

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,saaspanaderias-production.up.railway.app"
).split(",")

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "https://saaspanaderias-production.up.railway.app"
).split(",")


# =========================================================
# Application definition
# =========================================================

INSTALLED_APPS = [
    "design_system.apps.DesignSystemConfig",
    "core.apps.CoreConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    # Apps del sistema
    "conduces.apps.ConducesConfig",
    "inventario",
    "contabilidad",
    "tesoreria",
    "presupuesto",
    "rrhh",
    "nomina",
    "activos",
    "mantenimiento",
    'comercial',
    "documentos.apps.DocumentosConfig",
    "auditoria.apps.AuditoriaConfig",
    "catalogos.apps.CatalogosConfig",
    "compras.apps.ComprasConfig",
    "workflow.apps.WorkflowConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "panaderia_saas.urls"


# =========================================================
# Templates
# =========================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "panaderia_saas", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "conduces.context_processors.empresa_activa",
            ],
        },
    },
]

WSGI_APPLICATION = "panaderia_saas.wsgi.application"


# =========================================================
# Database
# =========================================================

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# Core transaccional. Todos los tiempos se expresan en segundos y pueden
# configurarse por entorno sin cambiar codigo.
CORE_IDEMPOTENCY_STALE_SECONDS = int(os.environ.get("CORE_IDEMPOTENCY_STALE_SECONDS", "900"))
CORE_IDEMPOTENCY_MAX_RETRIES = int(os.environ.get("CORE_IDEMPOTENCY_MAX_RETRIES", "3"))
CORE_DOUBLE_SUBMIT_WINDOW_SECONDS = int(os.environ.get("CORE_DOUBLE_SUBMIT_WINDOW_SECONDS", "5"))
CORE_EVENT_PROCESSING_TIMEOUT_SECONDS = int(os.environ.get("CORE_EVENT_PROCESSING_TIMEOUT_SECONDS", "900"))
CORE_EVENT_MAX_ATTEMPTS = int(os.environ.get("CORE_EVENT_MAX_ATTEMPTS", "5"))
CORE_EVENT_BATCH_SIZE = int(os.environ.get("CORE_EVENT_BATCH_SIZE", "100"))


# =========================================================
# Password validation
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =========================================================
# Internationalization
# =========================================================

LANGUAGE_CODE = "es-do"

TIME_ZONE = "America/Santo_Domingo"

USE_I18N = True

USE_TZ = True


# =========================================================
# Static files
# =========================================================

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# =========================================================
# Media files
# =========================================================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DOCUMENTOS_MAX_UPLOAD_SIZE = int(
    os.environ.get("DOCUMENTOS_MAX_UPLOAD_SIZE", 10 * 1024 * 1024)
)


# =========================================================
# Login / Logout
# =========================================================

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


# =========================================================
# Email SMTP Gmail Workspace / Railway
# =========================================================

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = os.environ.get(
    "EMAIL_HOST",
    "smtp.gmail.com"
)

EMAIL_PORT = int(
    os.environ.get("EMAIL_PORT", 587)
)

EMAIL_USE_TLS = os.environ.get(
    "EMAIL_USE_TLS",
    "True"
) == "True"

EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    "admin@saaspanaderias.com"
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    ""
)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "SaaS Panaderías <admin@saaspanaderias.com>"
)

EMAIL_TIMEOUT = 20


# =========================================================
# Default primary key field type
# =========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================================================
# Logging para Railway
# =========================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

USE_THOUSAND_SEPARATOR = True

THOUSAND_SEPARATOR = ","

DECIMAL_SEPARATOR = "."

NUMBER_GROUPING = 3
