"""
Django settings for panaderia_saas project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent

def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


DEBUG = env_bool("DEBUG", True)
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-local-development-only"
    else:
        raise ImproperlyConfigured("SECRET_KEY es obligatoria cuando DEBUG=False.")

SEDL_CATALOG_ENABLED = env_bool("SEDL_CATALOG_ENABLED", DEBUG)

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,saaspanaderias-production.up.railway.app"
).split(",")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "https://saaspanaderias-production.up.railway.app"
).split(",")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS if origin.strip()]

# Railway termina TLS en su proxy. Estos valores conservan desarrollo local
# sin HTTPS y endurecen cookies/redirecciones solamente en producción.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "3600" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)


# =========================================================
# Application definition
# =========================================================

INSTALLED_APPS = [
    "design_system.apps.DesignSystemConfig",
    "core.apps.CoreConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    # Apps del sistema
    "conduces.apps.ConducesConfig",
    "inventario",
    "contabilidad",
    "tesoreria",
    "presupuesto",
    "rrhh",
    "nomina",
    "activos",
    "mantenimiento",
    'comercial',
    "documentos.apps.DocumentosConfig",
    "auditoria.apps.AuditoriaConfig",
    "catalogos.apps.CatalogosConfig",
    "compras.apps.ComprasConfig",
    "workflow.apps.WorkflowConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "panaderia_saas.urls"


# =========================================================
# Templates
# =========================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "panaderia_saas", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "conduces.context_processors.empresa_activa",
            ],
        },
    },
]

WSGI_APPLICATION = "panaderia_saas.wsgi.application"


# =========================================================
# Database
# =========================================================

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# Core transaccional. Todos los tiempos se expresan en segundos y pueden
# configurarse por entorno sin cambiar codigo.
CORE_IDEMPOTENCY_STALE_SECONDS = int(os.environ.get("CORE_IDEMPOTENCY_STALE_SECONDS", "900"))
CORE_IDEMPOTENCY_MAX_RETRIES = int(os.environ.get("CORE_IDEMPOTENCY_MAX_RETRIES", "3"))
CORE_DOUBLE_SUBMIT_WINDOW_SECONDS = int(os.environ.get("CORE_DOUBLE_SUBMIT_WINDOW_SECONDS", "5"))
CORE_EVENT_PROCESSING_TIMEOUT_SECONDS = int(os.environ.get("CORE_EVENT_PROCESSING_TIMEOUT_SECONDS", "900"))
CORE_EVENT_MAX_ATTEMPTS = int(os.environ.get("CORE_EVENT_MAX_ATTEMPTS", "5"))
CORE_EVENT_BATCH_SIZE = int(os.environ.get("CORE_EVENT_BATCH_SIZE", "100"))


# =========================================================
# Password validation
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =========================================================
# Internationalization
# =========================================================

LANGUAGE_CODE = "es-do"

TIME_ZONE = "America/Santo_Domingo"

USE_I18N = True

USE_TZ = True


# =========================================================
# Static files
# =========================================================

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}


# =========================================================
# Media files
# =========================================================

MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", BASE_DIR / "media"))

DOCUMENTOS_MAX_UPLOAD_SIZE = int(
    os.environ.get("DOCUMENTOS_MAX_UPLOAD_SIZE", 10 * 1024 * 1024)
)
CALENDAR_PDF_MAX_MB = int(os.environ.get("CALENDAR_PDF_MAX_MB", "30"))


# =========================================================
# Login / Logout
# =========================================================

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


# =========================================================
# Transactional email (Resend HTTPS API) with legacy SMTP compatibility
# =========================================================

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "core.transactional_email.ResendEmailBackend"
)

RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
RESEND_API_URL = os.environ.get("RESEND_API_URL", "https://api.resend.com/emails")
RESEND_API_TIMEOUT = int(os.environ.get("RESEND_API_TIMEOUT", 15))

EMAIL_HOST = os.environ.get(
    "EMAIL_HOST",
    "smtp.gmail.com"
)

EMAIL_PORT = int(
    os.environ.get("EMAIL_PORT", 587)
)

EMAIL_USE_TLS = os.environ.get(
    "EMAIL_USE_TLS",
    "True"
) == "True"

EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    "admin@saaspanaderias.com"
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    ""
)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "SASTRE ERP <no-reply@notificaciones.saaspanaderias.com>"
)

EMAIL_TIMEOUT = 20


# =========================================================
# Default primary key field type
# =========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================================================
# Logging para Railway
# =========================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "conduces.verificacion_email": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "conduces.recuperacion_password": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

USE_THOUSAND_SEPARATOR = True

THOUSAND_SEPARATOR = ","

DECIMAL_SEPARATOR = "."

NUMBER_GROUPING = 3
