from django.conf import settings
from django.db import models
class Base(models.Model):
 empresa=models.ForeignKey("conduces.Empresa",on_delete=models.CASCADE);creado_en=models.DateTimeField(auto_now_add=True)
 class Meta:abstract=True
class PlanMantenimiento(Base):activo=models.ForeignKey("activos.ActivoFijo",on_delete=models.PROTECT);nombre=models.CharField(max_length=150);tipo=models.CharField(max_length=20);disparador=models.CharField(max_length=15);frecuencia=models.PositiveIntegerField();proxima_fecha=models.DateField(null=True);proxima_lectura=models.DecimalField(max_digits=14,decimal_places=2,null=True);activo_plan=models.BooleanField(default=True)
class TareaMantenimiento(models.Model):plan=models.ForeignKey(PlanMantenimiento,on_delete=models.CASCADE,related_name="tareas");nombre=models.CharField(max_length=150);instrucciones=models.TextField(blank=True);orden=models.PositiveIntegerField(default=0)
class OrdenMantenimiento(Base):numero=models.CharField(max_length=30);activo=models.ForeignKey("activos.ActivoFijo",on_delete=models.PROTECT);plan=models.ForeignKey(PlanMantenimiento,on_delete=models.PROTECT,null=True);tipo=models.CharField(max_length=20);estado=models.CharField(max_length=15,default="BORRADOR");programada_para=models.DateField();tecnico=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);proveedor=models.CharField(max_length=150,blank=True);costo_total=models.DecimalField(max_digits=18,decimal_places=2,default=0)
class DetalleOrdenMantenimiento(models.Model):orden=models.ForeignKey(OrdenMantenimiento,on_delete=models.CASCADE,related_name="detalles");tarea=models.ForeignKey(TareaMantenimiento,on_delete=models.PROTECT,null=True);descripcion=models.CharField(max_length=255);completada=models.BooleanField(default=False)
class MedidorActivo(Base):activo=models.ForeignKey("activos.ActivoFijo",on_delete=models.PROTECT);tipo=models.CharField(max_length=20);unidad=models.CharField(max_length=20);valor_actual=models.DecimalField(max_digits=14,decimal_places=2,default=0)
class LecturaMedidor(models.Model):medidor=models.ForeignKey(MedidorActivo,on_delete=models.CASCADE,related_name="lecturas");fecha=models.DateField();valor=models.DecimalField(max_digits=14,decimal_places=2)
class RepuestoMantenimiento(models.Model):orden=models.ForeignKey(OrdenMantenimiento,on_delete=models.CASCADE,related_name="repuestos");producto=models.ForeignKey("inventario.ProductoInventario",on_delete=models.PROTECT);cantidad=models.DecimalField(max_digits=14,decimal_places=4);costo=models.DecimalField(max_digits=18,decimal_places=2)
class CostoMantenimiento(models.Model):orden=models.ForeignKey(OrdenMantenimiento,on_delete=models.CASCADE,related_name="costos");tipo=models.CharField(max_length=20);descripcion=models.CharField(max_length=255);monto=models.DecimalField(max_digits=18,decimal_places=2)
class HistorialMantenimiento(models.Model):orden=models.ForeignKey(OrdenMantenimiento,on_delete=models.CASCADE,related_name="historial");estado_anterior=models.CharField(max_length=15);estado_nuevo=models.CharField(max_length=15);fecha=models.DateTimeField(auto_now_add=True)
