# Generated by Django 6.0.4 on 2026-08-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('conduces', '0029_empresa_modulo_inabie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaBancariaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('banco', models.CharField(max_length=120)),
                ('numero_enmascarado', models.CharField(max_length=40)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('saldo_banco', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_libros', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentabancariaempresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('beneficiario', models.CharField(max_length=180)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(default='EMITIDO', max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentabancariaempresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=60)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha', models.DateField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentabancariaempresa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlujoCajaProyectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=10)),
                ('origen', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InversionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.CharField(max_length=180)),
                ('instrumento', models.CharField(max_length=80)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tasa', models.DecimalField(decimal_places=4, max_digits=8)),
                ('vence_el', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.CharField(max_length=180)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=18)),
                ('utilizado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('referencia', models.CharField(max_length=100)),
                ('conciliado', models.BooleanField(default=False)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tesoreria.caja')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentabancariaempresa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineaConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_banco', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_libros', models.DecimalField(decimal_places=2, max_digits=18)),
                ('coincide', models.BooleanField(default=False)),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tesoreria.conciliacionbancaria')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tesoreria.movimientotesoreria')),
            ],
        ),
        migrations.CreateModel(
            name='PosicionTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('disponible', models.DecimalField(decimal_places=2, max_digits=18)),
                ('comprometido', models.DecimalField(decimal_places=2, max_digits=18)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrestamoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.CharField(max_length=180)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tasa', models.DecimalField(decimal_places=4, max_digits=8)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuotaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('vence_el', models.DateField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=18)),
                ('pagada', models.BooleanField(default=False)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='tesoreria.prestamofinanciero')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='tesoreria.cuentabancariaempresa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='tesoreria.cuentabancariaempresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
