# Generated by Django 6.0.4 on 2026-08-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('tesoreria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionExtractoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo', models.CharField(max_length=180)),
                ('formato', models.CharField(max_length=8)),
                ('huella', models.CharField(max_length=64)),
                ('estado', models.CharField(default='PREVISTA', max_length=15)),
                ('mapeo', models.JSONField(default=dict)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extractos_importados', to='tesoreria.cuentabancariaempresa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='LineaExtractoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('huella', models.CharField(max_length=64)),
                ('estado', models.CharField(default='PENDIENTE', max_length=15)),
                ('tipo_coincidencia', models.CharField(blank=True, max_length=20)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tesoreria.importacionextractobancario')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_extracto', to='tesoreria.movimientotesoreria')),
            ],
        ),
        migrations.AddConstraint(
            model_name='importacionextractobancario',
            constraint=models.UniqueConstraint(fields=('empresa', 'cuenta', 'huella'), name='tes_extracto_emp_cta_hash_uniq'),
        ),
        migrations.AddIndex(
            model_name='lineaextractobancario',
            index=models.Index(fields=['importacion', 'estado'], name='tes_linext_imp_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='lineaextractobancario',
            constraint=models.UniqueConstraint(fields=('importacion', 'huella'), name='tes_linea_extracto_hash_uniq'),
        ),
    ]
