from django.conf import settings
from django.db import models
class Base(models.Model):
 empresa=models.ForeignKey("conduces.Empresa",on_delete=models.CASCADE);creado_en=models.DateTimeField(auto_now_add=True)
 class Meta:abstract=True
class Departamento(Base):codigo=models.CharField(max_length=20);nombre=models.CharField(max_length=120);activo=models.BooleanField(default=True)
class Puesto(Base):codigo=models.CharField(max_length=20);nombre=models.CharField(max_length=120);descripcion=models.TextField(blank=True)
class CentroTrabajo(Base):codigo=models.CharField(max_length=20);nombre=models.CharField(max_length=120);direccion=models.TextField(blank=True)
class Empleado(Base):
 codigo=models.CharField(max_length=20);nombres=models.CharField(max_length=100);apellidos=models.CharField(max_length=100);identificacion=models.CharField(max_length=30);correo=models.EmailField(blank=True);telefono=models.CharField(max_length=30,blank=True);contacto_emergencia=models.CharField(max_length=150,blank=True);puesto=models.ForeignKey(Puesto,on_delete=models.PROTECT);departamento=models.ForeignKey(Departamento,on_delete=models.PROTECT);supervisor=models.ForeignKey("self",on_delete=models.PROTECT,null=True,blank=True);centro=models.ForeignKey(CentroTrabajo,on_delete=models.PROTECT);fecha_ingreso=models.DateField();salario=models.DecimalField(max_digits=18,decimal_places=2);forma_pago=models.CharField(max_length=20,default="TRANSFERENCIA");cuenta_bancaria_cifrada=models.TextField(blank=True);estado=models.CharField(max_length=15,default="ACTIVO");foto=models.ImageField(upload_to="rrhh/empleados/",blank=True)
 class Meta:constraints=[models.UniqueConstraint(fields=["empresa","codigo"],name="rrhh_emp_codigo_uniq"),models.UniqueConstraint(fields=["empresa","identificacion"],name="rrhh_emp_ident_uniq")]
class Organigrama(Base):empleado=models.OneToOneField(Empleado,on_delete=models.CASCADE);padre=models.ForeignKey("self",on_delete=models.PROTECT,null=True,blank=True)
class ContratoEmpleado(Base):empleado=models.ForeignKey(Empleado,on_delete=models.PROTECT,related_name="contratos");tipo=models.CharField(max_length=30);inicio=models.DateField();fin=models.DateField(null=True,blank=True);salario=models.DecimalField(max_digits=18,decimal_places=2);estado=models.CharField(max_length=15,default="BORRADOR")
class DependienteEmpleado(models.Model):empleado=models.ForeignKey(Empleado,on_delete=models.CASCADE,related_name="dependientes");nombre=models.CharField(max_length=150);parentesco=models.CharField(max_length=30);fecha_nacimiento=models.DateField(null=True)
class HistorialLaboral(models.Model):empleado=models.ForeignKey(Empleado,on_delete=models.CASCADE,related_name="historial");accion=models.CharField(max_length=40);snapshot=models.JSONField(default=dict);fecha=models.DateTimeField(auto_now_add=True)
class BeneficioEmpleado(Base):empleado=models.ForeignKey(Empleado,on_delete=models.CASCADE,related_name="beneficios");nombre=models.CharField(max_length=100);monto=models.DecimalField(max_digits=18,decimal_places=2,default=0)
class DocumentoEmpleado(Base):empleado=models.ForeignKey(Empleado,on_delete=models.CASCADE,related_name="documentos_rrhh");tipo=models.CharField(max_length=30);archivo=models.FileField(upload_to="rrhh/documentos/");vence_el=models.DateField(null=True,blank=True)
class AccionDisciplinaria(Base):empleado=models.ForeignKey(Empleado,on_delete=models.PROTECT);tipo=models.CharField(max_length=30);fecha=models.DateField();motivo=models.TextField()
class EvaluacionDesempeno(Base):empleado=models.ForeignKey(Empleado,on_delete=models.PROTECT);periodo=models.CharField(max_length=20);puntuacion=models.DecimalField(max_digits=5,decimal_places=2);comentarios=models.TextField(blank=True)
class Capacitacion(Base):nombre=models.CharField(max_length=150);inicio=models.DateField();fin=models.DateField();costo=models.DecimalField(max_digits=18,decimal_places=2,default=0)
class ParticipacionCapacitacion(models.Model):capacitacion=models.ForeignKey(Capacitacion,on_delete=models.CASCADE);empleado=models.ForeignKey(Empleado,on_delete=models.CASCADE);resultado=models.CharField(max_length=100,blank=True)
class SolicitudVacacion(Base):empleado=models.ForeignKey(Empleado,on_delete=models.PROTECT);desde=models.DateField();hasta=models.DateField();dias=models.DecimalField(max_digits=6,decimal_places=2);estado=models.CharField(max_length=15,default="BORRADOR")
class SaldoVacacion(models.Model):empleado=models.OneToOneField(Empleado,on_delete=models.CASCADE);disponibles=models.DecimalField(max_digits=6,decimal_places=2);tomados=models.DecimalField(max_digits=6,decimal_places=2,default=0)
class LicenciaEmpleado(Base):empleado=models.ForeignKey(Empleado,on_delete=models.PROTECT);tipo=models.CharField(max_length=30);desde=models.DateField();hasta=models.DateField();estado=models.CharField(max_length=15,default="APROBADA")
class AusenciaEmpleado(Base):empleado=models.ForeignKey(Empleado,on_delete=models.PROTECT);fecha=models.DateField();justificada=models.BooleanField(default=False)
class PermisoEmpleado(Base):empleado=models.ForeignKey(Empleado,on_delete=models.PROTECT);desde=models.DateTimeField();hasta=models.DateTimeField();estado=models.CharField(max_length=15,default="BORRADOR")
class HorarioTrabajo(Base):nombre=models.CharField(max_length=100);hora_entrada=models.TimeField();hora_salida=models.TimeField();dias=models.JSONField(default=list)
class TurnoTrabajo(Base):nombre=models.CharField(max_length=100);horario=models.ForeignKey(HorarioTrabajo,on_delete=models.PROTECT);recargo=models.DecimalField(max_digits=5,decimal_places=2,default=0)
class AsignacionTurno(Base):empleado=models.ForeignKey(Empleado,on_delete=models.PROTECT);turno=models.ForeignKey(TurnoTrabajo,on_delete=models.PROTECT);desde=models.DateField();hasta=models.DateField(null=True,blank=True)
class RegistroAsistencia(Base):empleado=models.ForeignKey(Empleado,on_delete=models.PROTECT);fecha=models.DateField();entrada=models.DateTimeField(null=True);salida=models.DateTimeField(null=True);minutos_tardanza=models.PositiveIntegerField(default=0);horas_trabajadas=models.DecimalField(max_digits=6,decimal_places=2,default=0)
class IncidenciaAsistencia(Base):registro=models.ForeignKey(RegistroAsistencia,on_delete=models.CASCADE);tipo=models.CharField(max_length=30);descripcion=models.TextField();aprobada=models.BooleanField(default=False)
class HoraExtra(Base):empleado=models.ForeignKey(Empleado,on_delete=models.PROTECT);fecha=models.DateField();horas=models.DecimalField(max_digits=6,decimal_places=2);factor=models.DecimalField(max_digits=5,decimal_places=2,default=1);estado=models.CharField(max_length=15,default="PENDIENTE")
class CalendarioLaboral(Base):anio=models.PositiveIntegerField();nombre=models.CharField(max_length=100)
class DiaFeriado(models.Model):calendario=models.ForeignKey(CalendarioLaboral,on_delete=models.CASCADE,related_name="feriados");fecha=models.DateField();nombre=models.CharField(max_length=120)
