# Generated by Django 6.0.4 on 2026-08-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anio', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=150)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=120)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='rrhh.calendariolaboral')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=150)),
                ('fecha_ingreso', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('forma_pago', models.CharField(default='TRANSFERENCIA', max_length=20)),
                ('cuenta_bancaria_cifrada', models.TextField(blank=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=15)),
                ('foto', models.ImageField(blank=True, upload_to='rrhh/empleados/')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.centrotrabajo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=30)),
                ('archivo', models.FileField(upload_to='rrhh/documentos/')),
                ('vence_el', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_rrhh', to='rrhh.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DependienteEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('parentesco', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependientes', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=30)),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='rrhh.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeneficioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='rrhh.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AusenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('justificada', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccionDisciplinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.CharField(max_length=20)),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=40)),
                ('snapshot', models.JSONField(default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('factor', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('estado', models.CharField(default='PENDIENTE', max_length=15)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('dias', models.JSONField(default=list)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=30)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('estado', models.CharField(default='APROBADA', max_length=15)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rrhh.organigrama')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipacionCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=100)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.capacitacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.puesto'),
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('entrada', models.DateTimeField(null=True)),
                ('salida', models.DateTimeField(null=True)),
                ('minutos_tardanza', models.PositiveIntegerField(default=0)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidenciaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('aprobada', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.registroasistencia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaldoVacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibles', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tomados', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('dias', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TurnoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.horariotrabajo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.turnotrabajo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='rrhh_emp_codigo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('empresa', 'identificacion'), name='rrhh_emp_ident_uniq'),
        ),
    ]
