# Generated by Django 6.0.4 on 2026-08-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciondisciplinaria',
            name='accion_tomada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acciondisciplinaria',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acciondisciplinaria',
            name='estado',
            field=models.CharField(default='ABIERTA', max_length=20),
        ),
        migrations.AddField(
            model_name='acciondisciplinaria',
            name='gravedad',
            field=models.CharField(default='MEDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='acciondisciplinaria',
            name='responsable',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='institucion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='modalidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='vence_el',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='jornada',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rrhh.puesto'),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='renovacion_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renovaciones', to='rrhh.contratoempleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='banco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='categoria_licencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='frecuencia_pago',
            field=models.CharField(default='MENSUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='licencia_conducir',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='empleado',
            name='vence_licencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acciondisciplinaria',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_disciplinarias', to='rrhh.empleado'),
        ),
        migrations.AlterField(
            model_name='participacioncapacitacion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='rrhh.empleado'),
        ),
        migrations.CreateModel(
            name='SalidaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateField()),
                ('tipo', models.CharField(max_length=30)),
                ('motivo', models.TextField()),
                ('ultima_fecha_laborada', models.DateField()),
                ('responsable', models.CharField(max_length=150)),
                ('comentarios', models.TextField(blank=True)),
                ('checklist', models.JSONField(default=dict)),
                ('activos_pendientes', models.BooleanField(default=False)),
                ('vacaciones_pendientes', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('estado', models.CharField(default='BORRADOR', max_length=20)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salida', to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
