# Generated by Django 6.0.4 on 2026-08-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_acciondisciplinaria_accion_tomada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciaempleado',
            name='motivo',
            field=models.TextField(blank=True),
        ),
    ]
