# Generated by Django 6.0.4 on 2026-08-20 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('rrhh', '0003_licenciaempleado_motivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_extra_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='horas_ordinarias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='nomina_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='tipo',
            field=models.CharField(default='ORDINARIA', max_length=30),
        ),
        migrations.AddField(
            model_name='incidenciaasistencia',
            name='aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_rrhh_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidenciaasistencia',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='incidenciaasistencia',
            name='minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidenciaasistencia',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidenciaasistencia',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='corregido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(default='ABIERTO', max_length=20),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='origen',
            field=models.CharField(default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='horaextra',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extra', to='rrhh.empleado'),
        ),
        migrations.AlterField(
            model_name='incidenciaasistencia',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='rrhh.registroasistencia'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponches', to='rrhh.empleado'),
        ),
        migrations.CreateModel(
            name='NovedadTSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.CharField(max_length=7)),
                ('tipo', models.CharField(max_length=30)),
                ('fecha_efectiva', models.DateField()),
                ('salario_reportable', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(default='BORRADOR', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_tss', to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReingresoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_reingreso', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tipo_contrato', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.centrotrabajo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.departamento')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reingresos', to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.puesto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CierreAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('estado', models.CharField(default='ABIERTO', max_length=20)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'desde', 'hasta'), name='rrhh_cierre_asistencia_uniq')],
            },
        ),
    ]
