# Generated by Django 6.0.4 on 2026-08-21 22:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def initialize_employee_sequences(apps, schema_editor):
    Employee = apps.get_model('rrhh', 'Empleado')
    Sequence = apps.get_model('rrhh', 'SecuenciaEmpleado')
    for company_id in Employee.objects.values_list('empresa_id', flat=True).distinct():
        highest = 0
        for code in Employee.objects.filter(empresa_id=company_id).values_list('codigo', flat=True):
            if code.startswith('EMP-') and code[4:].isdigit():
                highest = max(highest, int(code[4:]))
        Sequence.objects.update_or_create(empresa_id=company_id, defaults={'ultimo_numero': highest})


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('rrhh', '0004_horaextra_aprobador_horaextra_horas_ordinarias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoempleado',
            name='cargado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='documento_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones', to='rrhh.documentoempleado'),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='emitido_el',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='documentoempleado',
            name='archivo',
            field=models.FileField(upload_to='rrhh/documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.CreateModel(
            name='SecuenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveBigIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_empleados', to='conduces.empresa')),
            ],
        ),
        migrations.RunPython(initialize_employee_sequences, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DescripcionPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('objetivo', models.TextField()),
                ('funciones', models.TextField()),
                ('responsabilidades', models.TextField(blank=True)),
                ('procedimientos', models.TextField(blank=True)),
                ('herramientas', models.TextField(blank=True)),
                ('controles', models.TextField(blank=True)),
                ('documentos_relacionados', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('vigente_desde', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descripciones_funciones', to='rrhh.puesto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('puesto', 'version'), name='rrhh_desc_puesto_version_uniq')],
            },
        ),
    ]
