# Generated by Django 6.0.4 on 2026-08-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_documentoempleado_cargado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_cuenta_bancaria',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
