# Generated by Django 6.0.4 on 2026-08-22 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('rrhh', '0006_empleado_tipo_cuenta_bancaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrotrabajo',
            options={'verbose_name': 'Lugar de trabajo', 'verbose_name_plural': 'Lugares de trabajo'},
        ),
        migrations.AddField(
            model_name='centrotrabajo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centrotrabajo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='anexos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='lugar_prestacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='motivo_temporal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='numero',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='objeto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='departamento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='es_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EntidadFinancieraRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudDocumentoRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('LABORAL', 'Certificación laboral'), ('BANCARIA', 'Carta bancaria'), ('CONSULAR', 'Carta consular'), ('CONTRATO', 'Contrato'), ('TEMPORAL', 'Contrato temporal'), ('ANEXO', 'Anexo de funciones'), ('EXPEDIENTE', 'Expediente del empleado')], max_length=20)),
                ('destinatario', models.CharField(blank=True, max_length=180)),
                ('pais_destino', models.CharField(blank=True, max_length=100)),
                ('proposito', models.CharField(blank=True, max_length=180)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict)),
                ('estado', models.CharField(default='BORRADOR', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_documentos', to='rrhh.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('entidad_financiera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rrhh.entidadfinancierarrhh')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
