# Generated by Django 6.0.4 on 2026-08-23 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_alter_centrotrabajo_options_centrotrabajo_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoempleado',
            name='firmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='firmado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='firmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_rrhh_firmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='texto_firmado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='frecuencia_salario',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('QUINCENAL', 'Quincenal'), ('SEMANAL', 'Semanal'), ('ESPECIAL', 'Especial')], default='MENSUAL', max_length=20),
        ),
    ]
