# Generated by Django 6.0.4 on 2026-10-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0047_empresasaas_empresa_operativa'),
        ('rrhh', '0008_contratoempleado_firmado_contratoempleado_firmado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='puesto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='rrhh_puesto_empresa_codigo_uniq'),
        ),
    ]
