# Generated by Django 6.0.4 on 2026-05-25 22:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagofactoring',
            old_name='descripcion',
            new_name='observacion',
        ),
        migrations.RenameField(
            model_name='socio',
            old_name='fecha_creacion',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='factoring',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='aportesocio',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factoring',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factoring',
            name='monto_estimado_deposito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aportesocio',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='aportesocio',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aportesocio',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='contabilidad.socio'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='concepto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='concepto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='factoring',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('depositado', 'Depositado'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='factoring',
            name='numero_factura',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='concepto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='ncf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagofactoring',
            name='factoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='contabilidad.factoring'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
