# Generated by Django 6.0.4 on 2026-05-25 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_rename_descripcion_pagofactoring_observacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeudaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('empresa_debe', 'Empresa debe al socio'), ('socio_debe', 'Socio debe a la empresa')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='contabilidad.socio')),
            ],
        ),
    ]
