# Generated by Django 6.0.4 on 2026-05-26 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_deudasocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rnc', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBienesServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Factura606',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(max_length=30)),
                ('ncf_modificado', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_comprobante', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto_facturado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('itbis_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retencion_renta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retencion_itbis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20)),
                ('relacionado_empresa', models.BooleanField(default=True)),
                ('agregado_por_socio', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('socio_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.socio')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.proveedor')),
                ('tipo_bienes_servicios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.tipobienesservicios')),
            ],
        ),
    ]
