# Generated by Django 6.0.4 on 2026-05-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_proveedor_tipobienesservicios_factura606'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='consultado_dgii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado_dgii',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='municipio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='provincia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
