# Generated by Django 6.0.4 on 2026-08-02 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('compras', '0004_p2p03_permissions'),
        ('conduces', '0029_empresa_modulo_inabie'),
        ('contabilidad', '0005_proveedor_actividad_economica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnticipoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('COSTO', 'Costo'), ('GASTO', 'Gasto'), ('ORDEN', 'Orden')], max_length=12)),
                ('naturaleza', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=7)),
                ('acepta_movimientos', models.BooleanField(default=True)),
                ('es_control', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='contabilidad.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorPagarEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vence_el', models.DateField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=15)),
                ('bucket_aging', models.CharField(default='CORRIENTE', max_length=12)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuotaCxP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('vence_el', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='contabilidad.cuentaporpagarenterprise')),
            ],
        ),
        migrations.CreateModel(
            name='DiarioContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(default='GENERAL', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONTABILIZADO', 'Contabilizado'), ('REVERSADO', 'Reversado')], default='BORRADOR', max_length=15)),
                ('origen_tipo', models.CharField(blank=True, max_length=50)),
                ('origen_id', models.CharField(blank=True, max_length=50)),
                ('clave_idempotencia', models.CharField(max_length=180, unique=True)),
                ('total_debito', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_credito', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.diariocontable')),
            ],
            options={
                'permissions': [('contabilizar_asiento', 'Puede contabilizar asientos'), ('cerrar_periodo_contable', 'Puede cerrar períodos')],
            },
        ),
        migrations.CreateModel(
            name='DimensionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=50)),
                ('ncf', models.CharField(blank=True, max_length=30)),
                ('fecha', models.DateField()),
                ('vence_el', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(default='PENDIENTE', max_length=15)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.facturaproveedor')),
            ],
        ),
        migrations.AddField(
            model_name='cuentaporpagarenterprise',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_pagar', to='contabilidad.facturaproveedor'),
        ),
        migrations.CreateModel(
            name='HistorialAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contabilidad.asientocontable')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCxP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contabilidad.cuentaporpagarenterprise')),
            ],
        ),
        migrations.CreateModel(
            name='LineaAsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dimensiones', models.JSONField(blank=True, default=dict)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='LoteContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('origen', models.CharField(max_length=40)),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.lotecontable'),
        ),
        migrations.CreateModel(
            name='MovimientoCxP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.cuentaporpagarenterprise')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('motivo', models.TextField()),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.facturaproveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentaporpagarenterprise')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='contabilidad.ordenpago')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CierreContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.periodocontable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.periodocontable'),
        ),
        migrations.CreateModel(
            name='PlanCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('version', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='contabilidad.plancuenta'),
        ),
        migrations.CreateModel(
            name='PlantillaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('lineas', models.JSONField(default=list)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReglaContabilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(max_length=60)),
                ('version', models.PositiveIntegerField(default=1)),
                ('configuracion', models.JSONField(default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReversionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('asiento_origen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversion', to='contabilidad.asientocontable')),
                ('asiento_reversion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversa_de', to='contabilidad.asientocontable')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentaporpagarenterprise')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.solicitudpago'),
        ),
        migrations.CreateModel(
            name='ValorDimensionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='contabilidad.dimensioncontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='diariocontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='fin_diario_emp_cod_uniq'),
        ),
        migrations.AddConstraint(
            model_name='facturaproveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'proveedor', 'numero'), name='fin_facprov_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lineaasientocontable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credito', 0), ('debito__gt', 0)), models.Q(('credito__gt', 0), ('debito', 0)), _connector='OR'), name='fin_linea_un_lado'),
        ),
        migrations.AddConstraint(
            model_name='periodocontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'anio', 'mes'), name='fin_periodo_emp_anio_mes_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asientocontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='fin_asiento_emp_num_uniq'),
        ),
        migrations.AddConstraint(
            model_name='plancuenta',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo', 'version'), name='fin_plan_emp_cod_ver_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cuentacontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'plan', 'codigo'), name='fin_cuenta_emp_plan_cod_uniq'),
        ),
    ]
