# Generated by Django 6.0.4 on 2026-08-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_anticipoproveedor_cuentacontable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='requiere_centro_costo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='requiere_proyecto',
            field=models.BooleanField(default=False),
        ),
    ]
