# Generated by Django 6.0.4 on 2026-08-04 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_comparativocompra_adjudicacioncompra_and_more'),
        ('contabilidad', '0007_asientocontable_tasa_cambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporpagarenterprise',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentaporpagarenterprise',
            name='motivo_bloqueo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagarenterprise',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='detalle_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.detalleordencompraenterprise'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='anticipos_aplicados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='cargos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='dimensiones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='compras.ordencompraenterprise'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='compras.recepcioncompra'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('REGISTRADA', 'Registrada'), ('VALIDADA', 'Validada'), ('OBSERVADA', 'Observada'), ('PARCIALMENTE_PAGADA', 'Parcialmente Pagada'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada'), ('EN_DISPUTA', 'En Disputa')], default='BORRADOR', max_length=25),
        ),
    ]
