# Generated by Django 6.0.4 on 2026-08-04 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
        ('contabilidad', '0008_cuentaporpagarenterprise_bloqueada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDebitoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(default='REGISTRADA', max_length=15)),
                ('asiento_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagoMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('procesados', models.PositiveIntegerField(default=0)),
                ('fallidos', models.PositiveIntegerField(default=0)),
                ('resultado', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='anticipoproveedor',
            name='estado',
            field=models.CharField(default='DISPONIBLE', max_length=15),
        ),
        migrations.AddField(
            model_name='anticipoproveedor',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='asiento_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='estado',
            field=models.CharField(default='REGISTRADA', max_length=15),
        ),
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='retencion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='notacreditoproveedor',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='contabilidad.facturaproveedor'),
        ),
        migrations.AddConstraint(
            model_name='notacreditoproveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'factura', 'numero'), name='fin_ncprov_emp_fac_num_uniq'),
        ),
        migrations.AddField(
            model_name='notadebitoproveedor',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notadebitoproveedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='notadebitoproveedor',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_debito', to='contabilidad.facturaproveedor'),
        ),
        migrations.AddField(
            model_name='pagomasivo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagomasivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddConstraint(
            model_name='notadebitoproveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'factura', 'numero'), name='fin_ndprov_emp_fac_num_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pagomasivo',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='fin_pago_masivo_num_uniq'),
        ),
    ]
