# Generated by Django 6.0.4 on 2026-08-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_notadebitoproveedor_pagomasivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpago',
            name='metodo',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Deposito'), ('COMPENSACION', 'Compensacion')], default='TRANSFERENCIA', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='movimiento_tesoreria_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='retencion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
