# Generated by Django 6.0.4 on 2026-08-04 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_tasacambio'),
        ('compras', '0006_wizardsession_wizardaudittrail_wizardstepstate_and_more'),
        ('conduces', '0029_empresa_modulo_inabie'),
        ('contabilidad', '0010_ordenpago_metodo_ordenpago_movimiento_tesoreria_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetencionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('ITBIS', 'ITBIS'), ('ISR', 'ISR'), ('OTRA', 'Otra')], max_length=10)),
                ('codigo', models.CharField(max_length=30)),
                ('base', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=9)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APLICADA', 'Aplicada'), ('REVERSADA', 'Reversada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('clave_idempotencia', models.CharField(max_length=180)),
                ('asiento_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('motivo_reversion', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_aplicadas', to='contabilidad.facturaproveedor')),
                ('orden_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_aplicadas', to='contabilidad.ordenpago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
            options={
                'permissions': [('aplicar_retencion_proveedor', 'Puede aplicar retenciones'), ('revertir_retencion_proveedor', 'Puede revertir retenciones')],
            },
        ),
        migrations.CreateModel(
            name='CertificadoRetencionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=40)),
                ('contenido_hash', models.CharField(max_length=64)),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('retencion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificado', to='contabilidad.retencionproveedor')),
            ],
            options={
                'permissions': [('descargar_certificado_retencion', 'Puede descargar certificados de retencion')],
            },
        ),
        migrations.CreateModel(
            name='AplicacionRetencionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=18)),
                ('revertida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones', to='contabilidad.cuentaporpagarenterprise')),
                ('retencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='contabilidad.retencionproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CompensacionP2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('cuenta_cobrar_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tasa_cambio', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=18)),
                ('diferencia_cambiaria', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APLICADA', 'Aplicada'), ('REVERSADA', 'Reversada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('clave_idempotencia', models.CharField(max_length=180)),
                ('asiento_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('motivo_reversion', models.TextField(blank=True)),
                ('anticipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.anticipoproveedor')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta_pagar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensaciones', to='contabilidad.cuentaporpagarenterprise')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa')),
                ('nota_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.notacreditoproveedor')),
            ],
            options={
                'permissions': [('aplicar_compensacion_p2p', 'Puede aplicar compensaciones P2P'), ('revertir_compensacion_p2p', 'Puede revertir compensaciones P2P')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'numero'), name='fin_comp_p2p_num_uniq'), models.UniqueConstraint(fields=('empresa', 'clave_idempotencia'), name='fin_comp_p2p_idem_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='retencionproveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='fin_ret_prov_num_uniq'),
        ),
        migrations.AddConstraint(
            model_name='retencionproveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'clave_idempotencia'), name='fin_ret_prov_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='certificadoretencionproveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='fin_cert_ret_num_uniq'),
        ),
    ]
