# Generated by Django 6.0.4 on 2026-08-04 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_retencionproveedor_certificadoretencionproveedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='compensacionp2p',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROPUESTA', 'Propuesta'), ('APROBADA', 'Aprobada'), ('APLICADA', 'Aplicada'), ('REVERSADA', 'Reversada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12),
        ),
        migrations.CreateModel(
            name='HistorialCompensacionP2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=12)),
                ('estado_nuevo', models.CharField(max_length=12)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('compensacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contabilidad.compensacionp2p')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AplicacionAnticipoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tasa_cambio', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('diferencia_cambiaria', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('revertida', models.BooleanField(default=False)),
                ('clave_idempotencia', models.CharField(max_length=180)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('anticipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='contabilidad.anticipoproveedor')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_anticipo', to='contabilidad.cuentaporpagarenterprise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('anticipo', 'clave_idempotencia'), name='fin_aplic_ant_idem_uniq')],
            },
        ),
    ]
