# Generated by Django 6.0.4 on 2026-08-05 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_tasacambio'),
        ('contabilidad', '0012_notacreditoproveedor_saldo_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipoproveedor',
            name='tasa_cambio_snapshot',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='tasa_cambio_snapshot',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='notadebitoproveedor',
            name='concepto',
            field=models.CharField(default='RECARGO', max_length=15),
        ),
        migrations.AddField(
            model_name='notadebitoproveedor',
            name='tasa_cambio_snapshot',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='retencionproveedor',
            name='configuracion_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='retencionproveedor',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa'),
        ),
        migrations.AddField(
            model_name='retencionproveedor',
            name='tasa_cambio_snapshot',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='retencionproveedor',
            name='vigente_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retencionproveedor',
            name='vigente_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
