# Generated by Django 6.0.4 on 2026-08-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_anticipoproveedor_tasa_cambio_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencionproveedor',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente Aprobacion'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('APLICADA', 'Aplicada'), ('ANULADA', 'Anulada'), ('REVERTIDA', 'Revertida')], default='BORRADOR', max_length=24),
        ),
    ]
