# Generated by Django 6.0.4 on 2026-08-05 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_alter_retencionproveedor_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacreditoproveedor',
            name='estado',
            field=models.CharField(default='REGISTRADA', max_length=24),
        ),
        migrations.AlterField(
            model_name='notadebitoproveedor',
            name='estado',
            field=models.CharField(default='REGISTRADA', max_length=24),
        ),
        migrations.CreateModel(
            name='HistorialNotaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=24)),
                ('estado_nuevo', models.CharField(max_length=24)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contabilidad.notacreditoproveedor')),
                ('nota_debito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contabilidad.notadebitoproveedor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='AplicacionNotaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tasa_cambio', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('diferencia_cambiaria', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('clave_idempotencia', models.CharField(max_length=180)),
                ('asiento_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('revertida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_notas', to='contabilidad.cuentaporpagarenterprise')),
                ('nota_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='contabilidad.notacreditoproveedor')),
                ('nota_debito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='contabilidad.notadebitoproveedor')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('nota_credito__isnull', False), ('nota_debito__isnull', True)), models.Q(('nota_credito__isnull', True), ('nota_debito__isnull', False)), _connector='OR'), name='fin_aplic_nota_un_tipo'), models.UniqueConstraint(fields=('cuenta', 'clave_idempotencia'), name='fin_aplic_nota_idem_uniq')],
            },
        ),
    ]
