# Generated by Django 6.0.4 on 2026-08-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_alter_notacreditoproveedor_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipoproveedor',
            name='estado',
            field=models.CharField(default='DISPONIBLE', max_length=24),
        ),
    ]
