from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils import timezone
import uuid

from .models import AuditMixin


class OfertaProveedor(AuditMixin):
    ESTADOS=[(x,x.replace("_"," ").title()) for x in ("BORRADOR","ENVIADA","ACLARACION_SOLICITADA","ACTUALIZADA","RETIRADA","VENCIDA","DESCALIFICADA","EVALUADA","CERRADA")]
    rfq=models.ForeignKey("compras.ProcesoRFQ",on_delete=models.PROTECT,related_name="ofertas");proveedor=models.ForeignKey("compras.Proveedor",on_delete=models.PROTECT,related_name="ofertas");numero=models.CharField(max_length=30);version=models.PositiveIntegerField(default=1);estado=models.CharField(max_length=25,choices=ESTADOS,default="BORRADOR");moneda=models.ForeignKey("catalogos.MonedaEmpresa",on_delete=models.PROTECT);tasa_cambio=models.DecimalField(max_digits=18,decimal_places=6,default=1);fecha_oferta=models.DateField();valida_hasta=models.DateField();plazo_entrega_dias=models.PositiveIntegerField(default=0);garantia_dias=models.PositiveIntegerField(default=0);subtotal=models.DecimalField(max_digits=18,decimal_places=2,default=0);descuento=models.DecimalField(max_digits=18,decimal_places=2,default=0);impuesto=models.DecimalField(max_digits=18,decimal_places=2,default=0);total=models.DecimalField(max_digits=18,decimal_places=2,default=0);score_tecnico=models.DecimalField(max_digits=7,decimal_places=2,default=0);score_economico=models.DecimalField(max_digits=7,decimal_places=2,default=0);score_total=models.DecimalField(max_digits=7,decimal_places=2,default=0);observaciones=models.TextField(blank=True);enviada_en=models.DateTimeField(null=True,blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","numero","version"],name="p2p_oferta_num_ver_uniq"),models.UniqueConstraint(fields=["rfq","proveedor","version"],name="p2p_oferta_rfq_prov_ver_uniq")];permissions=[("enviar_oferta","Puede enviar ofertas"),("evaluar_oferta","Puede evaluar ofertas"),("descalificar_oferta","Puede descalificar ofertas")]

class LineaOferta(models.Model):
    oferta=models.ForeignKey(OfertaProveedor,on_delete=models.CASCADE,related_name="lineas");linea_rfq=models.ForeignKey("compras.DetalleRFQ",on_delete=models.PROTECT);cantidad=models.DecimalField(max_digits=18,decimal_places=4);precio_unitario=models.DecimalField(max_digits=18,decimal_places=4);descuento=models.DecimalField(max_digits=18,decimal_places=2,default=0);impuesto=models.DecimalField(max_digits=18,decimal_places=2,default=0);total=models.DecimalField(max_digits=18,decimal_places=2);marca=models.CharField(max_length=100,blank=True);modelo=models.CharField(max_length=100,blank=True);cumple=models.BooleanField(default=True);observaciones=models.TextField(blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["oferta","linea_rfq"],name="p2p_linea_oferta_uniq"),models.CheckConstraint(condition=Q(cantidad__gt=0,precio_unitario__gte=0),name="p2p_linea_oferta_pos")]

class VersionOferta(models.Model):
    oferta=models.ForeignKey(OfertaProveedor,on_delete=models.CASCADE,related_name="versiones");version=models.PositiveIntegerField();snapshot=models.JSONField();hash_contenido=models.CharField(max_length=64);creado_en=models.DateTimeField(auto_now_add=True);creado_por=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["oferta","version"],name="p2p_ver_oferta_uniq")]
class HistorialOferta(models.Model):
    oferta=models.ForeignKey(OfertaProveedor,on_delete=models.CASCADE,related_name="historial");estado_anterior=models.CharField(max_length=25);estado_nuevo=models.CharField(max_length=25);comentario=models.TextField(blank=True);usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);fecha=models.DateTimeField(auto_now_add=True)
class AclaracionOferta(models.Model):
    oferta=models.ForeignKey(OfertaProveedor,on_delete=models.CASCADE,related_name="aclaraciones");pregunta=models.TextField();respuesta=models.TextField(blank=True);estado=models.CharField(max_length=15,default="PENDIENTE");solicitada_por=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,related_name="+");respondida_por=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True,related_name="+");creado_en=models.DateTimeField(auto_now_add=True);respondido_en=models.DateTimeField(null=True,blank=True)

class ComparativoCompra(AuditMixin):
    expediente=models.ForeignKey("compras.ExpedienteCompra",on_delete=models.PROTECT,related_name="comparativos");rfq=models.ForeignKey("compras.ProcesoRFQ",on_delete=models.PROTECT,related_name="comparativos");numero=models.CharField(max_length=30);version=models.PositiveIntegerField(default=1);estado=models.CharField(max_length=15,default="BORRADOR");ponderaciones=models.JSONField(default=dict);snapshot=models.JSONField(default=dict);recomendacion=models.TextField(blank=True);congelado_en=models.DateTimeField(null=True,blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","numero","version"],name="p2p_comp_num_ver_uniq")];permissions=[("recalcular_comparativo","Puede recalcular comparativos"),("congelar_comparativo","Puede congelar comparativos"),("exportar_comparativo","Puede exportar comparativos")]
class LineaComparativo(models.Model):
    comparativo=models.ForeignKey(ComparativoCompra,on_delete=models.CASCADE,related_name="lineas");oferta=models.ForeignKey(OfertaProveedor,on_delete=models.PROTECT);proveedor=models.ForeignKey("compras.Proveedor",on_delete=models.PROTECT);precio=models.DecimalField(max_digits=18,decimal_places=2);impuestos=models.DecimalField(max_digits=18,decimal_places=2,default=0);descuentos=models.DecimalField(max_digits=18,decimal_places=2,default=0);plazo=models.DecimalField(max_digits=7,decimal_places=2,default=0);entrega=models.DecimalField(max_digits=7,decimal_places=2,default=0);garantia=models.DecimalField(max_digits=7,decimal_places=2,default=0);calidad=models.DecimalField(max_digits=7,decimal_places=2,default=0);cumplimiento=models.DecimalField(max_digits=7,decimal_places=2,default=0);riesgo=models.DecimalField(max_digits=7,decimal_places=2,default=0);capacidad=models.DecimalField(max_digits=7,decimal_places=2,default=0);respuesta=models.DecimalField(max_digits=7,decimal_places=2,default=0);documentacion=models.DecimalField(max_digits=7,decimal_places=2,default=0);score_tecnico=models.DecimalField(max_digits=7,decimal_places=2,default=0);score_economico=models.DecimalField(max_digits=7,decimal_places=2,default=0);score_total=models.DecimalField(max_digits=7,decimal_places=2,default=0);posicion=models.PositiveIntegerField(default=0);explicacion=models.TextField(blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["comparativo","oferta"],name="p2p_linea_comp_oferta_uniq")]
class EscenarioComparativo(models.Model):
    comparativo=models.ForeignKey(ComparativoCompra,on_delete=models.CASCADE,related_name="escenarios");nombre=models.CharField(max_length=100);ponderaciones=models.JSONField();resultados=models.JSONField(default=dict);creado_por=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);creado_en=models.DateTimeField(auto_now_add=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["comparativo","nombre"],name="p2p_escenario_nombre_uniq")]
class HistorialComparativo(models.Model):
    comparativo=models.ForeignKey(ComparativoCompra,on_delete=models.CASCADE,related_name="historial");accion=models.CharField(max_length=30);snapshot=models.JSONField(default=dict);usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);fecha=models.DateTimeField(auto_now_add=True)

class AdjudicacionCompra(AuditMixin):
    TIPOS=[(x,x.title()) for x in ("TOTAL","PARCIAL","MULTIPLE","DESIERTA","CANCELADA")];expediente=models.ForeignKey("compras.ExpedienteCompra",on_delete=models.PROTECT,related_name="adjudicaciones");comparativo=models.ForeignKey(ComparativoCompra,on_delete=models.PROTECT,null=True,blank=True,related_name="adjudicaciones");numero=models.CharField(max_length=30);version=models.PositiveIntegerField(default=1);tipo=models.CharField(max_length=12,choices=TIPOS);estado=models.CharField(max_length=25,default="BORRADOR");justificacion=models.TextField();snapshot=models.JSONField(default=dict);workflow_instancia=models.ForeignKey("workflow.InstanciaWorkflow",on_delete=models.SET_NULL,null=True,blank=True);aprobada_en=models.DateTimeField(null=True,blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","numero","version"],name="p2p_adj_num_ver_uniq")];permissions=[("aprobar_adjudicacion","Puede aprobar adjudicaciones"),("cancelar_adjudicacion","Puede cancelar adjudicaciones")]
class DetalleAdjudicacion(models.Model):
    adjudicacion=models.ForeignKey(AdjudicacionCompra,on_delete=models.CASCADE,related_name="detalles");linea_rfq=models.ForeignKey("compras.DetalleRFQ",on_delete=models.PROTECT);oferta=models.ForeignKey(OfertaProveedor,on_delete=models.PROTECT);proveedor=models.ForeignKey("compras.Proveedor",on_delete=models.PROTECT);cantidad=models.DecimalField(max_digits=18,decimal_places=4);precio_unitario=models.DecimalField(max_digits=18,decimal_places=4);total=models.DecimalField(max_digits=18,decimal_places=2)
class HistorialAdjudicacion(models.Model):
    adjudicacion=models.ForeignKey(AdjudicacionCompra,on_delete=models.CASCADE,related_name="historial");estado_anterior=models.CharField(max_length=25);estado_nuevo=models.CharField(max_length=25);usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);comentario=models.TextField(blank=True);fecha=models.DateTimeField(auto_now_add=True)

class OrdenCompraEnterprise(AuditMixin):
    ESTADOS=[(x,x.replace("_"," ").title()) for x in ("BORRADOR","PENDIENTE_APROBACION","APROBADA","ENVIADA","ACEPTADA","PARCIALMENTE_RECIBIDA","RECIBIDA","PARCIALMENTE_FACTURADA","FACTURADA","CERRADA","CANCELADA")];numero=models.CharField(max_length=30);adjudicacion=models.ForeignKey(AdjudicacionCompra,on_delete=models.PROTECT,null=True,blank=True,related_name="ordenes");proveedor=models.ForeignKey("compras.Proveedor",on_delete=models.PROTECT,related_name="ordenes_enterprise");moneda=models.ForeignKey("catalogos.MonedaEmpresa",on_delete=models.PROTECT);tasa_cambio=models.DecimalField(max_digits=18,decimal_places=6,default=1);version=models.PositiveIntegerField(default=1);estado=models.CharField(max_length=30,choices=ESTADOS,default="BORRADOR");fecha=models.DateField();entrega_desde=models.DateField();entrega_hasta=models.DateField();subtotal=models.DecimalField(max_digits=18,decimal_places=2,default=0);descuento=models.DecimalField(max_digits=18,decimal_places=2,default=0);impuesto=models.DecimalField(max_digits=18,decimal_places=2,default=0);total=models.DecimalField(max_digits=18,decimal_places=2,default=0);dimensiones=models.JSONField(default=dict,blank=True);workflow_instancia=models.ForeignKey("workflow.InstanciaWorkflow",on_delete=models.SET_NULL,null=True,blank=True);observaciones=models.TextField(blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","numero","version"],name="p2p_orden_num_ver_uniq")];permissions=[("aprobar_orden_compra","Puede aprobar órdenes"),("crear_orden_directa","Puede crear órdenes directas"),("cancelar_orden_compra","Puede cancelar órdenes")]
class DetalleOrdenCompraEnterprise(models.Model):
    orden=models.ForeignKey(OrdenCompraEnterprise,on_delete=models.CASCADE,related_name="detalles");linea_adjudicacion=models.ForeignKey(DetalleAdjudicacion,on_delete=models.PROTECT,null=True,blank=True);producto=models.ForeignKey("inventario.ProductoInventario",on_delete=models.PROTECT,null=True,blank=True);descripcion=models.CharField(max_length=300);cantidad=models.DecimalField(max_digits=18,decimal_places=4);cantidad_recibida=models.DecimalField(max_digits=18,decimal_places=4,default=0);cantidad_facturada=models.DecimalField(max_digits=18,decimal_places=4,default=0);precio_unitario=models.DecimalField(max_digits=18,decimal_places=4);descuento=models.DecimalField(max_digits=18,decimal_places=2,default=0);impuesto=models.DecimalField(max_digits=18,decimal_places=2,default=0);total=models.DecimalField(max_digits=18,decimal_places=2);almacen=models.ForeignKey("catalogos.Almacen",on_delete=models.PROTECT,null=True,blank=True)
class VersionOrdenCompra(models.Model):
    orden=models.ForeignKey(OrdenCompraEnterprise,on_delete=models.CASCADE,related_name="versiones");version=models.PositiveIntegerField();snapshot=models.JSONField();creado_por=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);creado_en=models.DateTimeField(auto_now_add=True)
class HistorialOrdenCompra(models.Model):
    orden=models.ForeignKey(OrdenCompraEnterprise,on_delete=models.CASCADE,related_name="historial");estado_anterior=models.CharField(max_length=30);estado_nuevo=models.CharField(max_length=30);comentario=models.TextField(blank=True);usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);fecha=models.DateTimeField(auto_now_add=True)

class RecepcionCompra(AuditMixin):
    ESTADOS=[(x,x.replace("_"," ").title()) for x in ("BORRADOR","EN_PROCESO","PARCIAL","COMPLETA","CON_DIFERENCIAS","RECHAZADA","DEVUELTA","CANCELADA")];numero=models.CharField(max_length=30);orden=models.ForeignKey(OrdenCompraEnterprise,on_delete=models.PROTECT,related_name="recepciones");estado=models.CharField(max_length=25,choices=ESTADOS,default="BORRADOR");fecha=models.DateTimeField();almacen=models.ForeignKey("catalogos.Almacen",on_delete=models.PROTECT);documento_proveedor=models.CharField(max_length=100,blank=True);observaciones=models.TextField(blank=True);cerrada_en=models.DateTimeField(null=True,blank=True);reabierta_en=models.DateTimeField(null=True,blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","numero"],name="p2p_recepcion_num_uniq")];permissions=[("cerrar_recepcion","Puede cerrar recepciones"),("reabrir_recepcion","Puede reabrir recepciones")]
class DetalleRecepcionCompra(models.Model):
    recepcion=models.ForeignKey(RecepcionCompra,on_delete=models.CASCADE,related_name="detalles");detalle_orden=models.ForeignKey(DetalleOrdenCompraEnterprise,on_delete=models.PROTECT);cantidad_recibida=models.DecimalField(max_digits=18,decimal_places=4);cantidad_aceptada=models.DecimalField(max_digits=18,decimal_places=4);cantidad_rechazada=models.DecimalField(max_digits=18,decimal_places=4,default=0);lote=models.CharField(max_length=80,blank=True);serie=models.CharField(max_length=120,blank=True);vence_el=models.DateField(null=True,blank=True);dañado=models.BooleanField(default=False);motivo_diferencia=models.TextField(blank=True);movimiento_inventario_id=models.PositiveBigIntegerField(null=True,blank=True)
class InspeccionRecepcion(models.Model):
    recepcion=models.ForeignKey(RecepcionCompra,on_delete=models.CASCADE,related_name="inspecciones");resultado=models.CharField(max_length=20);observaciones=models.TextField(blank=True);evidencias=models.JSONField(default=list);inspeccionado_por=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);fecha=models.DateTimeField(auto_now_add=True)
class DevolucionCompra(AuditMixin):
    recepcion=models.ForeignKey(RecepcionCompra,on_delete=models.PROTECT,related_name="devoluciones");numero=models.CharField(max_length=30);estado=models.CharField(max_length=20,default="BORRADOR");motivo=models.TextField();fecha=models.DateTimeField();procesada_en=models.DateTimeField(null=True,blank=True)
class DetalleDevolucionCompra(models.Model):
    devolucion=models.ForeignKey(DevolucionCompra,on_delete=models.CASCADE,related_name="detalles");detalle_recepcion=models.ForeignKey(DetalleRecepcionCompra,on_delete=models.PROTECT);cantidad=models.DecimalField(max_digits=18,decimal_places=4);movimiento_inventario_id=models.PositiveBigIntegerField(null=True,blank=True)

class WizardSession(models.Model):
    TIPOS=[(x,x.replace("_"," ").title()) for x in ("COMPRA","RECEPCION","FACTURA_PAGO")]
    ESTADOS=[(x,x.title()) for x in ("ACTIVO","COMPLETADO","CANCELADO","EXPIRADO","FALLIDO")]
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);empresa=models.ForeignKey("conduces.Empresa",on_delete=models.CASCADE);usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE);tipo=models.CharField(max_length=20,choices=TIPOS);estado=models.CharField(max_length=12,choices=ESTADOS,default="ACTIVO");paso_actual=models.PositiveSmallIntegerField(default=1);total_pasos=models.PositiveSmallIntegerField();clave_idempotencia=models.CharField(max_length=180);datos=models.JSONField(default=dict,blank=True);resultado_tipo=models.CharField(max_length=80,blank=True);resultado_id=models.CharField(max_length=80,blank=True);creado_en=models.DateTimeField(auto_now_add=True);actualizado_en=models.DateTimeField(auto_now=True);expira_en=models.DateTimeField()
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","usuario","tipo","clave_idempotencia"],name="p2p_wizard_idem_uniq")];permissions=[("operar_wizard_p2p","Puede operar wizards P2P")]
    @property
    def expirada(self):return self.expira_en<=timezone.now()

class WizardStepState(models.Model):
    sesion=models.ForeignKey(WizardSession,on_delete=models.CASCADE,related_name="pasos");numero=models.PositiveSmallIntegerField();nombre=models.CharField(max_length=100);estado=models.CharField(max_length=12,default="PENDIENTE");datos=models.JSONField(default=dict,blank=True);validado_en=models.DateTimeField(null=True,blank=True);actualizado_en=models.DateTimeField(auto_now=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["sesion","numero"],name="p2p_wizard_step_uniq")];ordering=["numero"]

class WizardAuditTrail(models.Model):
    sesion=models.ForeignKey(WizardSession,on_delete=models.CASCADE,related_name="auditoria");usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);accion=models.CharField(max_length=30);paso=models.PositiveSmallIntegerField(null=True,blank=True);metadata_segura=models.JSONField(default=dict,blank=True);fecha=models.DateTimeField(auto_now_add=True)
    class Meta:default_permissions=("view",);ordering=["fecha"]
    def save(self,*a,**k):
        if self.pk:raise ValueError("La auditoria del wizard es inmutable.")
        return super().save(*a,**k)
