# Generated by Django 6.0.4 on 2026-08-02 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('conduces', '0029_empresa_modulo_inabie'),
        ('inventario', '0013_alter_ejecucioninventarioorden_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidorActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=20)),
                ('unidad', models.CharField(max_length=20)),
                ('valor_actual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.activofijo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LecturaMedidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='mantenimiento.medidoractivo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(default='BORRADOR', max_length=15)),
                ('programada_para', models.DateField()),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.activofijo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='mantenimiento.ordenmantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='CostoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='mantenimiento.ordenmantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=20)),
                ('disparador', models.CharField(max_length=15)),
                ('frecuencia', models.PositiveIntegerField()),
                ('proxima_fecha', models.DateField(null=True)),
                ('proxima_lectura', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('activo_plan', models.BooleanField(default=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.activofijo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.planmantenimiento'),
        ),
        migrations.CreateModel(
            name='RepuestoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='mantenimiento.ordenmantenimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
            ],
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('instrucciones', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mantenimiento.planmantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('completada', models.BooleanField(default=False)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mantenimiento.ordenmantenimiento')),
                ('tarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.tareamantenimiento')),
            ],
        ),
    ]
