# Generated by Django 6.0.4 on 2026-07-29 01:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conduces', '0026_dianodocencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('tipo_cliente', models.CharField(choices=[('CENTRO_EDUCATIVO', 'Centro educativo'), ('DISTRITO_ESCOLAR', 'Distrito escolar'), ('REGIONAL_EDUCATIVA', 'Regional educativa'), ('INSTITUCION_GUBERNAMENTAL', 'Institución gubernamental'), ('CLIENTE_PRIVADO', 'Cliente privado'), ('SUPERMERCADO', 'Supermercado'), ('COLMADO', 'Colmado'), ('RESTAURANTE', 'Restaurante'), ('DISTRIBUIDOR', 'Distribuidor'), ('CONSUMIDOR_FINAL', 'Consumidor final'), ('OTRO', 'Otro')], max_length=40)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('rnc_cedula', models.CharField(blank=True, max_length=30, verbose_name='RNC o cédula')),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion_fiscal', models.TextField(blank=True)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('requiere_ncf', models.BooleanField(default=False)),
                ('tipo_comprobante_preferido', models.CharField(blank=True, max_length=30)),
                ('contribuyente', models.BooleanField(default=False)),
                ('condicion_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('MIXTO', 'Mixto')], default='CONTADO', max_length=10)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('lista_precio', models.CharField(blank=True, max_length=100)),
                ('vendedor_asignado', models.CharField(blank=True, max_length=150)),
                ('ruta_asignada', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO_CREDITO', 'Bloqueado por crédito'), ('EN_EVALUACION', 'En evaluación')], default='ACTIVO', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_comerciales', to='conduces.empresa')),
            ],
            options={
                'ordering': ['nombre_comercial', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('es_principal', models.BooleanField(default=False)),
                ('recibe_facturas', models.BooleanField(default=False)),
                ('recibe_cobros', models.BooleanField(default=False)),
                ('recibe_entregas', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='comercial.cliente')),
            ],
            options={
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('FISCAL', 'Fiscal'), ('ENTREGA', 'Entrega'), ('COBRO', 'Cobro'), ('OTRO', 'Otro')], max_length=10)),
                ('direccion', models.TextField()),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('referencia', models.TextField(blank=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('contacto_recepcion', models.CharField(blank=True, max_length=150)),
                ('telefono_recepcion', models.CharField(blank=True, max_length=50)),
                ('horario_recepcion', models.CharField(blank=True, max_length=150)),
                ('instrucciones_entrega', models.TextField(blank=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='comercial.cliente')),
            ],
            options={
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'estado'], name='com_cli_emp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'nombre_comercial'], name='com_cli_emp_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'rnc_cedula'], name='com_cli_emp_rnc_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='comercial_cliente_empresa_codigo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('limite_credito__gte', 0)), name='comercial_cliente_limite_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_maximo__gte', 0), ('descuento_maximo__lte', 100)), name='comercial_cliente_descuento_rango'),
        ),
        migrations.AddConstraint(
            model_name='direccioncliente',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('es_principal', True)), fields=('cliente', 'tipo'), name='comercial_direccion_principal_activa_uniq'),
        ),
    ]
