# Generated by Django 6.0.4 on 2026-07-29 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
        ('conduces', '0026_dianodocencia'),
        ('inventario', '0008_productoinventario_afecta_produccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega_desde', models.TimeField(blank=True, null=True)),
                ('hora_entrega_hasta', models.TimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('condicion_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('MIXTO', 'Mixto')], max_length=10)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
                ('lista_precio', models.CharField(blank=True, max_length=100)),
                ('moneda', models.CharField(choices=[('DOP', 'DOP'), ('USD', 'USD')], default='DOP', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('observaciones_cliente', models.TextField(blank=True)),
                ('observaciones_internas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('EN_PREPARACION', 'En preparación'), ('LISTO_DESPACHO', 'Listo para despacho'), ('DESPACHADO', 'Despachado'), ('ENTREGADO_PARCIAL', 'Entregado parcial'), ('ENTREGADO', 'Entregado'), ('FACTURADO', 'Facturado')], default='BORRADOR', max_length=30)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='comercial.cliente')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.contactocliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
                ('direccion_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.direccioncliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='conduces.empresa')),
                ('rechazado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_rechazados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_pedido', '-id'],
                'permissions': [('aprobar_pedido', 'Puede aprobar pedidos'), ('rechazar_pedido', 'Puede rechazar pedidos'), ('cancelar_pedido', 'Puede cancelar pedidos')],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('EN_PREPARACION', 'En preparación'), ('LISTO_DESPACHO', 'Listo para despacho'), ('DESPACHADO', 'Despachado'), ('ENTREGADO_PARCIAL', 'Entregado parcial'), ('ENTREGADO', 'Entregado'), ('FACTURADO', 'Facturado')], max_length=30)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('EN_PREPARACION', 'En preparación'), ('LISTO_DESPACHO', 'Listo para despacho'), ('DESPACHADO', 'Despachado'), ('ENTREGADO_PARCIAL', 'Entregado parcial'), ('ENTREGADO', 'Entregado'), ('FACTURADO', 'Facturado')], max_length=30)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='comercial.pedido')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comercial.pedido')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SecuenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('periodo', models.PositiveIntegerField()),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa', 'estado'], name='com_ped_emp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa', 'fecha_entrega'], name='com_ped_emp_entrega_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='com_pedido_empresa_numero_uniq'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='com_detalle_pedido_producto_uniq'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='com_detalle_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='com_detalle_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_descuento__gte', 0), ('porcentaje_descuento__lte', 100)), name='com_detalle_descuento_rango'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_impuesto__gte', 0), ('porcentaje_impuesto__lte', 100)), name='com_detalle_impuesto_rango'),
        ),
        migrations.AddConstraint(
            model_name='secuenciadocumento',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo', 'periodo'), name='com_secuencia_empresa_tipo_periodo_uniq'),
        ),
    ]
