# Generated by Django 6.0.4 on 2026-07-31 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_pedido_historialestadopedido_detallepedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secuenciadocumento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secuenciadocumento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuenciadocumento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuenciadocumento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='secuenciadocumento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='secuenciadocumento',
            name='fecha_ultima_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secuenciadocumento',
            name='longitud',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='secuenciadocumento',
            name='prefijo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='secuenciadocumento',
            name='reinicia_anualmente',
            field=models.BooleanField(default=True),
        ),
    ]
