# Generated by Django 6.0.4 on 2026-08-02 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_configuracioncomercialempresa_equipocomercial_and_more'),
        ('conduces', '0029_empresa_modulo_inabie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionPoliticaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_politica', models.CharField(max_length=40)),
                ('objeto_id', models.PositiveBigIntegerField()),
                ('codigo', models.CharField(max_length=30)),
                ('version', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=12)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('prioridad', models.PositiveIntegerField()),
                ('contenido', models.JSONField()),
                ('hash_contenido', models.CharField(max_length=64)),
                ('motivo', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones_politicas_comerciales', to='conduces.empresa')),
                ('version_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.versionpoliticacomercial')),
            ],
            options={
                'ordering': ['tipo_politica', 'codigo', '-version'],
                'permissions': [('versionar_politica_comercial', 'Puede versionar políticas comerciales')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo_politica', 'codigo', 'version'), name='com_verpol_emp_tipo_cod_ver_uniq')],
            },
        ),
    ]
