# Generated by Django 6.0.4 on 2026-08-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_versionpoliticacomercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicacomision',
            name='ambito',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicacomision',
            name='reglas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicacredito',
            name='ambito',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicacredito',
            name='reglas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicadescuento',
            name='ambito',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicadescuento',
            name='reglas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicadevolucion',
            name='ambito',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicadevolucion',
            name='reglas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicaentrega',
            name='ambito',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicaentrega',
            name='reglas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicafacturacion',
            name='ambito',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='politicafacturacion',
            name='reglas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
