# Generated by Django 6.0.4 on 2026-08-02 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('comercial', '0007_actividadcomercial_fuenteprospecto_and_more'),
        ('conduces', '0029_empresa_modulo_inabie'),
        ('inventario', '0013_alter_ejecucioninventarioorden_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADA_INTERNA', 'Aprobada interna'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('CONVERTIDA', 'Convertida')], default='BORRADOR', max_length=20)),
                ('fecha', models.DateField()),
                ('valida_hasta', models.DateField()),
                ('condicion_pago', models.CharField(blank=True, max_length=100)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'permissions': [('aprobar_cotizacion_venta', 'Puede aprobar cotizaciones'), ('versionar_cotizacion_venta', 'Puede versionar cotizaciones'), ('convertir_cotizacion_venta', 'Puede convertir cotizaciones'), ('exportar_cotizacion_venta', 'Puede exportar cotizaciones'), ('administrar_cotizacion_venta', 'Puede administrar cotizaciones')],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('snapshot', models.JSONField(default=dict)),
                ('hash_precio', models.CharField(blank=True, max_length=64)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(blank=True, max_length=100)),
                ('cantidad_minima', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('cantidad_maxima', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCotizacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('INACTIVA', 'Inactiva')], default='BORRADOR', max_length=10)),
                ('predeterminada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['prioridad', 'nombre'],
                'permissions': [('activar_lista_precio', 'Puede activar listas de precio'), ('versionar_lista_precio', 'Puede versionar listas de precio'), ('simular_precio_comercial', 'Puede simular precios'), ('administrar_pricing', 'Puede administrar pricing')],
            },
        ),
        migrations.CreateModel(
            name='PoliticaDescuentoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('porcentaje_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('requiere_aprobacion_desde', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion_venta', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('presentacion', models.CharField(blank=True, max_length=100)),
                ('unidad_venta', models.CharField(max_length=30)),
                ('factor_conversion', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('venta_minima', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('multiplo_venta', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('permite_descuento', models.BooleanField(default=True)),
                ('precio_base', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('imagen', models.ImageField(blank=True, upload_to='comercial/productos/')),
                ('ficha', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('disponible_venta', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': [('administrar_producto_comercial', 'Puede administrar productos comerciales'), ('exportar_producto_comercial', 'Puede exportar productos comerciales')],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('hora_desde', models.TimeField(blank=True, null=True)),
                ('hora_hasta', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRAMADA', 'Programada'), ('REPROGRAMADA', 'Reprogramada'), ('CANCELADA', 'Cancelada'), ('ENVIADA_A_PREPARACION', 'Enviada a preparación')], default='PENDIENTE', max_length=25)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha_programada', 'pedido__numero'],
                'permissions': [('programar_pedido_comercial', 'Puede programar pedidos'), ('reprogramar_pedido_comercial', 'Puede reprogramar pedidos')],
            },
        ),
        migrations.CreateModel(
            name='PromocionComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('administrar_promocion_comercial', 'Puede administrar promociones')],
            },
        ),
        migrations.CreateModel(
            name='ReglaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('FIJO', 'Precio fijo'), ('VOLUMEN', 'Precio por volumen'), ('RECARGO', 'Recargo'), ('DESCUENTO', 'Descuento'), ('ESPECIAL', 'Precio especial'), ('BONIFICACION', 'Bonificación futura')], max_length=15)),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('condiciones', models.JSONField(default=dict)),
                ('accion', models.JSONField(default=dict)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('administrar_regla_precio', 'Puede administrar reglas de precio')],
            },
        ),
        migrations.CreateModel(
            name='ReglaPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_minima', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio_especial', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionCotizacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('hash_contenido', models.CharField(max_length=64)),
                ('motivo', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_comercial', 'codigo'], 'permissions': [('bloquear_credito_cliente', 'Puede bloquear crédito de clientes'), ('gestionar_credito_cliente', 'Puede gestionar crédito de clientes'), ('calcular_riesgo_cliente', 'Puede calcular riesgo de clientes'), ('administrar_cliente_360', 'Puede administrar Cliente 360'), ('exportar_cliente_360', 'Puede exportar Cliente 360')]},
        ),
        migrations.AddField(
            model_name='cliente',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='comercial.canalventa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='categoria_riesgo',
            field=models.CharField(default='MEDIO', max_length=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='comercial.clasificacioncliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicion_pago_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_comerciales', to='catalogos.condicionpago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='credito_utilizado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cliente',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='comercial.equipocomercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='exento_impuestos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='explicacion_riesgo',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_calculo_riesgo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='moneda_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_comerciales', to='catalogos.monedaempresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='retenciones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='comercial.rutacomercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='score_riesgo',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='comercial.segmentocliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='comercial.vendedorcomercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='version_formula_riesgo',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='comercial.zonacomercial'),
        ),
        migrations.AddField(
            model_name='contactocliente',
            name='recibe_cobranzas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactocliente',
            name='recibe_compras',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='direccioncliente',
            name='tipo',
            field=models.CharField(choices=[('FISCAL', 'Fiscal'), ('ENTREGA', 'Entrega'), ('COBRO', 'Cobro'), ('OTRO', 'Otro'), ('SUCURSAL', 'Sucursal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historialestadopedido',
            name='estado_anterior',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('EN_PREPARACION', 'En preparación'), ('LISTO_DESPACHO', 'Listo para despacho'), ('DESPACHADO', 'Despachado'), ('ENTREGADO_PARCIAL', 'Entregado parcial'), ('ENTREGADO', 'Entregado'), ('FACTURADO', 'Facturado'), ('EN_PROGRAMACION', 'En programación'), ('PROGRAMADO', 'Programado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historialestadopedido',
            name='estado_nuevo',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('EN_PREPARACION', 'En preparación'), ('LISTO_DESPACHO', 'Listo para despacho'), ('DESPACHADO', 'Despachado'), ('ENTREGADO_PARCIAL', 'Entregado parcial'), ('ENTREGADO', 'Entregado'), ('FACTURADO', 'Facturado'), ('EN_PROGRAMACION', 'En programación'), ('PROGRAMADO', 'Programado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('EN_PREPARACION', 'En preparación'), ('LISTO_DESPACHO', 'Listo para despacho'), ('DESPACHADO', 'Despachado'), ('ENTREGADO_PARCIAL', 'Entregado parcial'), ('ENTREGADO', 'Entregado'), ('FACTURADO', 'Facturado'), ('EN_PROGRAMACION', 'En programación'), ('PROGRAMADO', 'Programado')], default='BORRADOR', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('credito_utilizado__gte', 0)), name='com_cliente_credito_util_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('score_riesgo__gte', 0), ('score_riesgo__lte', 100)), name='com_cliente_score_rango'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('rnc_cedula', ''), _negated=True), fields=('empresa', 'rnc_cedula'), name='com_cliente_emp_ident_uniq'),
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='comercial.cliente'),
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_venta', to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa'),
        ),
        migrations.AddField(
            model_name='cotizacionventa',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='comercial.oportunidadcomercial'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotizacion_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_convertido', to='comercial.cotizacionventa'),
        ),
        migrations.AddField(
            model_name='detallecotizacionventa',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comercial.cotizacionventa'),
        ),
        migrations.AddField(
            model_name='historialcotizacionventa',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='comercial.cotizacionventa'),
        ),
        migrations.AddField(
            model_name='historialcotizacionventa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='historialcotizacionventa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.canalventa'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.cliente'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precio_comerciales', to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='segmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.segmentocliente'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='version_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.listaprecio'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.zonacomercial'),
        ),
        migrations.AddField(
            model_name='detallelistaprecio',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comercial.listaprecio'),
        ),
        migrations.AddField(
            model_name='politicadescuentocomercial',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='productocomercial',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.canalventa'),
        ),
        migrations.AddField(
            model_name='productocomercial',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_comerciales', to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='productocomercial',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.impuesto'),
        ),
        migrations.AddField(
            model_name='productocomercial',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa'),
        ),
        migrations.AddField(
            model_name='productocomercial',
            name='producto_inventario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='producto_comercial', to='inventario.productoinventario'),
        ),
        migrations.AddField(
            model_name='detallelistaprecio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.productocomercial'),
        ),
        migrations.AddField(
            model_name='detallecotizacionventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.productocomercial'),
        ),
        migrations.AddField(
            model_name='programacionpedido',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programacionpedido',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programacionpedido',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_comerciales', to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='programacionpedido',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='programacion_comercial', to='comercial.pedido'),
        ),
        migrations.AddField(
            model_name='programacionpedido',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.rutacomercial'),
        ),
        migrations.AddField(
            model_name='programacionpedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.vendedorcomercial'),
        ),
        migrations.AddField(
            model_name='programacionpedido',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.zonacomercial'),
        ),
        migrations.AddField(
            model_name='promocioncomercial',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='reglaprecio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='reglapromocion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.productocomercial'),
        ),
        migrations.AddField(
            model_name='reglapromocion',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='comercial.promocioncomercial'),
        ),
        migrations.AddField(
            model_name='versioncotizacionventa',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='comercial.cotizacionventa'),
        ),
        migrations.AddField(
            model_name='versioncotizacionventa',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versioncotizacionventa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddIndex(
            model_name='cotizacionventa',
            index=models.Index(fields=['empresa', 'estado'], name='com_cot_emp_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotizacionventa',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='com_cot_emp_num_uniq'),
        ),
        migrations.AddIndex(
            model_name='listaprecio',
            index=models.Index(fields=['empresa', 'estado', 'vigencia_desde'], name='com_lista_emp_est_vig_idx'),
        ),
        migrations.AddConstraint(
            model_name='listaprecio',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo', 'version'), name='com_lista_emp_cod_ver_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productocomercial',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='com_prodcom_emp_cod_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productocomercial',
            constraint=models.CheckConstraint(condition=models.Q(('factor_conversion__gt', 0), ('multiplo_venta__gt', 0), ('venta_minima__gt', 0)), name='com_prodcom_factores_pos'),
        ),
        migrations.AddConstraint(
            model_name='productocomercial',
            constraint=models.CheckConstraint(condition=models.Q(('precio_base__gte', 0)), name='com_prodcom_precio_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='detallelistaprecio',
            constraint=models.UniqueConstraint(fields=('lista', 'producto', 'presentacion', 'cantidad_minima'), name='com_detlista_unico'),
        ),
        migrations.AddConstraint(
            model_name='detallelistaprecio',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_minima__gt', 0), ('precio__gte', 0)), name='com_detlista_valores_pos'),
        ),
        migrations.AddConstraint(
            model_name='detallecotizacionventa',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0), ('precio_unitario__gte', 0)), name='com_detcot_valores_pos'),
        ),
        migrations.AddIndex(
            model_name='programacionpedido',
            index=models.Index(fields=['empresa', 'fecha_programada', 'estado'], name='com_prog_emp_fecha_est_idx'),
        ),
        migrations.AddConstraint(
            model_name='promocioncomercial',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='com_promo_emp_cod_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reglaprecio',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='com_regprecio_emp_cod_uniq'),
        ),
        migrations.AddConstraint(
            model_name='versioncotizacionventa',
            constraint=models.UniqueConstraint(fields=('cotizacion', 'version'), name='com_vercot_cot_ver_uniq'),
        ),
    ]
