# Generated by Django 6.0.4 on 2026-08-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_detallepreparacionpedido_cuentaporcobrar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesionfactoring',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cesionfactoring',
            name='costo_financiero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cesionfactoring',
            name='desembolsado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cesionfactoring',
            name='neto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cesionfactoring',
            name='referencia_desembolso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cesionfactoring',
            name='retencion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cesionfactoring',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='cesionfactoring',
            name='vence_el',
            field=models.DateField(blank=True, null=True),
        ),
    ]
