# Generated by Django 6.0.4 on 2026-08-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_cesionfactoring_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='dimensiones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='recibocobro',
            name='dimensiones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recibocobro',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
    ]
