# Generated by Django 6.0.4 on 2026-08-03 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_tasacambio'),
        ('comercial', '0011_facturaventa_dimensiones_facturaventa_tasa_cambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacioncobro',
            name='diferencia_cambiaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='aplicacioncobro',
            name='monto_moneda_cobro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='aplicacioncobro',
            name='tasa_cobro',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='aplicacioncobro',
            name='tasa_factura',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='cesionfactoring',
            name='dimensiones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cesionfactoring',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa'),
        ),
        migrations.AddField(
            model_name='notacreditoventa',
            name='dimensiones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notacreditoventa',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa'),
        ),
        migrations.AddField(
            model_name='notacreditoventa',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='notadebitoventa',
            name='dimensiones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notadebitoventa',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.monedaempresa'),
        ),
        migrations.AddField(
            model_name='notadebitoventa',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
    ]
