from django.db import models
class Base(models.Model):
 empresa=models.ForeignKey("conduces.Empresa",on_delete=models.CASCADE);creado_en=models.DateTimeField(auto_now_add=True)
 class Meta:abstract=True
class CategoriaActivo(Base):codigo=models.CharField(max_length=20);nombre=models.CharField(max_length=120);tipo=models.CharField(max_length=20);vida_util_meses=models.PositiveIntegerField();tasa_residual=models.DecimalField(max_digits=5,decimal_places=2,default=0)
class UbicacionActivo(Base):codigo=models.CharField(max_length=20);nombre=models.CharField(max_length=120);direccion=models.TextField(blank=True)
class ActivoFijo(Base):codigo=models.CharField(max_length=30);nombre=models.CharField(max_length=180);categoria=models.ForeignKey(CategoriaActivo,on_delete=models.PROTECT);ubicacion=models.ForeignKey(UbicacionActivo,on_delete=models.PROTECT);fecha_adquisicion=models.DateField();costo=models.DecimalField(max_digits=18,decimal_places=2);valor_residual=models.DecimalField(max_digits=18,decimal_places=2,default=0);depreciacion_acumulada=models.DecimalField(max_digits=18,decimal_places=2,default=0);metodo=models.CharField(max_length=20,default="LINEA_RECTA");vida_util_meses=models.PositiveIntegerField();estado=models.CharField(max_length=15,default="ACTIVO")
class ComponenteActivo(models.Model):activo=models.ForeignKey(ActivoFijo,on_delete=models.CASCADE,related_name="componentes");nombre=models.CharField(max_length=150);costo=models.DecimalField(max_digits=18,decimal_places=2);vida_util_meses=models.PositiveIntegerField()
class AsignacionActivo(Base):activo=models.ForeignKey(ActivoFijo,on_delete=models.PROTECT);empleado=models.ForeignKey("rrhh.Empleado",on_delete=models.PROTECT,null=True);desde=models.DateField();hasta=models.DateField(null=True)
class MovimientoActivo(Base):activo=models.ForeignKey(ActivoFijo,on_delete=models.PROTECT);tipo=models.CharField(max_length=20);origen=models.ForeignKey(UbicacionActivo,on_delete=models.PROTECT,null=True,related_name="salidas");destino=models.ForeignKey(UbicacionActivo,on_delete=models.PROTECT,null=True,related_name="entradas");fecha=models.DateField()
class MejoraActivo(Base):activo=models.ForeignKey(ActivoFijo,on_delete=models.PROTECT);fecha=models.DateField();monto=models.DecimalField(max_digits=18,decimal_places=2);descripcion=models.TextField()
class RevaluacionActivo(Base):activo=models.ForeignKey(ActivoFijo,on_delete=models.PROTECT);fecha=models.DateField();valor_anterior=models.DecimalField(max_digits=18,decimal_places=2);valor_nuevo=models.DecimalField(max_digits=18,decimal_places=2);motivo=models.TextField()
class DepreciacionActivo(Base):activo=models.ForeignKey(ActivoFijo,on_delete=models.PROTECT,related_name="depreciaciones");periodo=models.DateField();monto=models.DecimalField(max_digits=18,decimal_places=2);acumulada=models.DecimalField(max_digits=18,decimal_places=2);valor_libros=models.DecimalField(max_digits=18,decimal_places=2)
class BajaActivo(Base):activo=models.OneToOneField(ActivoFijo,on_delete=models.PROTECT);fecha=models.DateField();tipo=models.CharField(max_length=20);valor_recuperado=models.DecimalField(max_digits=18,decimal_places=2,default=0);motivo=models.TextField()
class SeguroActivo(Base):activo=models.ForeignKey(ActivoFijo,on_delete=models.PROTECT,related_name="seguros");aseguradora=models.CharField(max_length=150);poliza=models.CharField(max_length=60);desde=models.DateField();hasta=models.DateField();cobertura=models.DecimalField(max_digits=18,decimal_places=2)
class GarantiaActivo(Base):activo=models.ForeignKey(ActivoFijo,on_delete=models.PROTECT,related_name="garantias");proveedor=models.CharField(max_length=150);desde=models.DateField();hasta=models.DateField();descripcion=models.TextField(blank=True)
class DocumentoActivo(Base):activo=models.ForeignKey(ActivoFijo,on_delete=models.CASCADE,related_name="documentos_activo");tipo=models.CharField(max_length=30);archivo=models.FileField(upload_to="activos/documentos/")
class HistorialActivo(models.Model):activo=models.ForeignKey(ActivoFijo,on_delete=models.CASCADE,related_name="historial");accion=models.CharField(max_length=40);snapshot=models.JSONField(default=dict);fecha=models.DateTimeField(auto_now_add=True)
