# Generated by Django 6.0.4 on 2026-07-31 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('conduces', '0028_empresa_modulo_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('estrategia_asignacion', models.CharField(default='DECLARATIVA', max_length=30)),
                ('estrategia_decision', models.CharField(choices=[('CUALQUIERA', 'Cualquiera'), ('UNANIMIDAD', 'Unanimidad'), ('MAYORIA_SIMPLE', 'Mayoría simple'), ('MINIMO_VOTOS', 'Mínimo de votos'), ('TODOS_LOS_ASIGNADOS', 'Todos'), ('PRIMERA_RESPUESTA', 'Primera respuesta')], max_length=24)),
                ('minimo_aprobaciones', models.PositiveIntegerField(default=1)),
                ('porcentaje_mayoria', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('rechazo_finaliza', models.BooleanField(default=True)),
                ('permite_devolucion', models.BooleanField(default=True)),
                ('permite_delegacion', models.BooleanField(default=False)),
                ('permite_suplencia', models.BooleanField(default=True)),
                ('requiere_comentario_aprobacion', models.BooleanField(default=False)),
                ('requiere_comentario_rechazo', models.BooleanField(default=True)),
                ('requiere_comentario_devolucion', models.BooleanField(default=True)),
                ('dias_objetivo', models.PositiveIntegerField(blank=True, null=True)),
                ('horas_objetivo', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'ordering': ['orden', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AsignadorNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('USUARIO', 'Usuario'), ('GRUPO', 'Grupo'), ('PERMISO', 'Permiso'), ('ROL_EMPRESA', 'Rol Empresa'), ('SUPERVISOR_SOLICITANTE', 'Supervisor Solicitante'), ('RESPONSABLE_CENTRO_COSTO', 'Responsable Centro Costo'), ('RESPONSABLE_AREA', 'Responsable Area'), ('DINAMICO_ADAPTADOR', 'Dinamico Adaptador')], max_length=30)),
                ('permiso_codename', models.CharField(blank=True, max_length=100)),
                ('rol_codigo', models.CharField(blank=True, max_length=80)),
                ('parametro', models.CharField(blank=True, max_length=160)),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignadores', to='workflow.nivelaprobacion')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReglaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('dominio', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('RETIRADA', 'Retirada')], default='BORRADOR', max_length=12)),
                ('prioridad', models.PositiveIntegerField(default=0)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('requiere_presupuesto', models.BooleanField(default=False)),
                ('permite_autoaprobacion', models.BooleanField(default=False)),
                ('permite_reapertura', models.BooleanField(default=False)),
                ('permite_devolucion', models.BooleanField(default=True)),
                ('rechazo_finaliza', models.BooleanField(default=True)),
                ('comentario_obligatorio_aprobacion', models.BooleanField(default=False)),
                ('comentario_obligatorio_rechazo', models.BooleanField(default=True)),
                ('comentario_obligatorio_devolucion', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'ordering': ['dominio', 'tipo_documento', '-prioridad', '-version'],
                'permissions': [('versionar_regla_aprobacion', 'Puede versionar reglas'), ('activar_regla_aprobacion', 'Puede activar reglas'), ('retirar_regla_aprobacion', 'Puede retirar reglas'), ('validar_regla_aprobacion', 'Puede validar reglas'), ('gestionar_asignadores_workflow', 'Puede gestionar asignadores'), ('gestionar_suplencias_workflow', 'Puede gestionar suplencias'), ('iniciar_workflow', 'Puede iniciar workflows'), ('aprobar_workflow', 'Puede aprobar'), ('rechazar_workflow', 'Puede rechazar'), ('devolver_workflow', 'Puede devolver'), ('cancelar_workflow', 'Puede cancelar'), ('reabrir_workflow', 'Puede reabrir'), ('reasignar_workflow', 'Puede reasignar'), ('view_historial_workflow', 'Puede ver historial'), ('view_tareas_workflow', 'Puede ver tareas'), ('administrar_workflow', 'Puede administrar workflow'), ('exportar_workflow', 'Puede exportar workflow')],
            },
        ),
        migrations.AddField(
            model_name='nivelaprobacion',
            name='regla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveles', to='workflow.reglaaprobacion'),
        ),
        migrations.CreateModel(
            name='CondicionReglaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('campo', models.CharField(max_length=80)),
                ('operador', models.CharField(choices=[('IGUAL', 'Igual'), ('DIFERENTE', 'Diferente'), ('MAYOR_QUE', 'Mayor Que'), ('MAYOR_O_IGUAL', 'Mayor O Igual'), ('MENOR_QUE', 'Menor Que'), ('MENOR_O_IGUAL', 'Menor O Igual'), ('EN_LISTA', 'En Lista'), ('NO_EN_LISTA', 'No En Lista'), ('CONTIENE', 'Contiene'), ('NO_CONTIENE', 'No Contiene'), ('ES_NULO', 'Es Nulo'), ('NO_ES_NULO', 'No Es Nulo')], max_length=20)),
                ('valor_tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('DECIMAL', 'Decimal'), ('ENTERO', 'Entero'), ('BOOLEANO', 'Booleano'), ('FECHA', 'Fecha'), ('LISTA', 'Lista')], max_length=10)),
                ('valor_texto', models.TextField(blank=True)),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('valor_entero', models.BigIntegerField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('agrupador', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condiciones', to='workflow.reglaaprobacion')),
            ],
            options={
                'ordering': ['agrupador', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SuplenciaAprobador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vigente_desde', models.DateTimeField()),
                ('vigente_hasta', models.DateTimeField()),
                ('alcance', models.CharField(choices=[('GLOBAL', 'Global'), ('DOMINIO', 'Dominio'), ('TIPO_DOCUMENTO', 'Tipo documental'), ('REGLA', 'Regla')], max_length=20)),
                ('dominio', models.CharField(blank=True, max_length=50)),
                ('tipo_documento', models.CharField(blank=True, max_length=80)),
                ('motivo', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.reglaaprobacion')),
                ('suplente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suplencias_suplente', to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suplencias_titular', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='reglaaprobacion',
            index=models.Index(fields=['empresa', 'dominio', 'tipo_documento'], name='wf_regla_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='reglaaprobacion',
            index=models.Index(fields=['empresa', 'estado'], name='wf_regla_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='reglaaprobacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo', 'version'), name='wf_regla_emp_cod_ver_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reglaaprobacion',
            constraint=models.UniqueConstraint(condition=models.Q(('es_predeterminada', True), ('estado', 'ACTIVA')), fields=('empresa', 'dominio', 'tipo_documento'), name='wf_regla_default_activa_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reglaaprobacion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='wf_regla_version_pos'),
        ),
        migrations.AddConstraint(
            model_name='nivelaprobacion',
            constraint=models.UniqueConstraint(fields=('regla', 'numero'), name='wf_nivel_regla_num_uniq'),
        ),
        migrations.AddConstraint(
            model_name='nivelaprobacion',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='wf_nivel_num_pos'),
        ),
        migrations.AddIndex(
            model_name='suplenciaaprobador',
            index=models.Index(fields=['empresa', 'titular', 'activa'], name='wf_suplencia_vig_idx'),
        ),
        migrations.AddConstraint(
            model_name='suplenciaaprobador',
            constraint=models.CheckConstraint(condition=models.Q(('titular', models.F('suplente')), _negated=True), name='wf_suplencia_distintos'),
        ),
        migrations.AddConstraint(
            model_name='suplenciaaprobador',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__gt', models.F('vigente_desde'))), name='wf_suplencia_vigencia'),
        ),
    ]
