# Generated by Django 6.0.4 on 2026-07-31 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0028_empresa_modulo_workflow'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla_version', models.PositiveIntegerField()),
                ('object_id', models.PositiveBigIntegerField()),
                ('referencia_externa', models.CharField(blank=True, max_length=160)),
                ('proposito', models.CharField(default='APROBACION', max_length=80)),
                ('dominio', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=80)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('INICIADA', 'Iniciada'), ('EN_APROBACION', 'En Aprobacion'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('DEVUELTA', 'Devuelta'), ('CANCELADA', 'Cancelada'), ('ERROR', 'Error')], default='BORRADOR', max_length=20)),
                ('nivel_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=30)),
                ('motivo_final', models.TextField(blank=True)),
                ('contexto_snapshot', models.JSONField(default=dict)),
                ('documento_snapshot', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('iniciada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows_iniciados', to=settings.AUTH_USER_MODEL)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='workflow.reglaaprobacion')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NivelInstanciaWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('nombre_snapshot', models.CharField(max_length=120)),
                ('estrategia_decision', models.CharField(choices=[('CUALQUIERA', 'Cualquiera'), ('UNANIMIDAD', 'Unanimidad'), ('MAYORIA_SIMPLE', 'Mayoría simple'), ('MINIMO_VOTOS', 'Mínimo de votos'), ('TODOS_LOS_ASIGNADOS', 'Todos'), ('PRIMERA_RESPUESTA', 'Primera respuesta')], max_length=24)),
                ('minimo_aprobaciones', models.PositiveIntegerField(default=1)),
                ('porcentaje_mayoria', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('rechazo_finaliza', models.BooleanField(default=True)),
                ('permite_devolucion', models.BooleanField(default=True)),
                ('requiere_comentario_aprobacion', models.BooleanField(default=False)),
                ('requiere_comentario_rechazo', models.BooleanField(default=True)),
                ('requiere_comentario_devolucion', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('DEVUELTO', 'Devuelto'), ('OMITIDO', 'Omitido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=12)),
                ('activado_en', models.DateTimeField(blank=True, null=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('vencimiento_objetivo', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=30)),
                ('motivo', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveles_instancia', to='workflow.instanciaworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('origen_tipo', models.CharField(max_length=30)),
                ('origen_referencia', models.CharField(blank=True, max_length=160)),
                ('es_titular', models.BooleanField(default=True)),
                ('es_suplente', models.BooleanField(default=False)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('revocada', models.BooleanField(default=False)),
                ('motivo_revocacion', models.TextField(blank=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_workflow', to=settings.AUTH_USER_MODEL)),
                ('usuario_titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_representadas', to=settings.AUTH_USER_MODEL)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='workflow.instanciaworkflow')),
                ('nivel_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='workflow.nivelinstanciaworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='RondaWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('motivo', models.TextField(blank=True)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('iniciada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rondas', to='workflow.instanciaworkflow')),
            ],
        ),
        migrations.AddField(
            model_name='nivelinstanciaworkflow',
            name='ronda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveles', to='workflow.rondaworkflow'),
        ),
        migrations.CreateModel(
            name='DecisionAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APROBAR', 'Aprobar'), ('RECHAZAR', 'Rechazar'), ('DEVOLVER', 'Devolver'), ('ABSTENERSE', 'Abstenerse')], max_length=12)),
                ('comentario', models.TextField(blank=True)),
                ('metadata_segura', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones', to='workflow.asignacionaprobacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario_efectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_workflow', to=settings.AUTH_USER_MODEL)),
                ('usuario_representado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_representadas', to=settings.AUTH_USER_MODEL)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones', to='workflow.instanciaworkflow')),
                ('nivel_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones', to='workflow.nivelinstanciaworkflow')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones', to='workflow.rondaworkflow')),
            ],
            options={
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='SolicitudCorreccionWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=12)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('atendida_en', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True)),
                ('version_documento_anterior', models.CharField(blank=True, max_length=80)),
                ('version_documento_nueva', models.CharField(blank=True, max_length=80)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_atendidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='workflow.instanciaworkflow')),
                ('nivel_instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.nivelinstanciaworkflow')),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='instanciaworkflow',
            index=models.Index(fields=['empresa', 'estado'], name='wf_inst_emp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='instanciaworkflow',
            index=models.Index(fields=['content_type', 'object_id'], name='wf_inst_obj_idx'),
        ),
        migrations.AddConstraint(
            model_name='instanciaworkflow',
            constraint=models.UniqueConstraint(fields=('empresa', 'idempotency_key'), name='wf_inst_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='instanciaworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ('BORRADOR', 'INICIADA', 'EN_APROBACION', 'DEVUELTA'))), fields=('empresa', 'content_type', 'object_id', 'proposito'), name='wf_inst_doc_activa_uniq'),
        ),
        migrations.AddIndex(
            model_name='asignacionaprobacion',
            index=models.Index(fields=['empresa', 'usuario', 'activa'], name='wf_asig_tarea_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacionaprobacion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('revocada', False)), fields=('nivel_instancia', 'usuario'), name='wf_asig_usuario_activa_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rondaworkflow',
            constraint=models.UniqueConstraint(fields=('instancia', 'numero'), name='wf_ronda_inst_num_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rondaworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('instancia',), name='wf_ronda_activa_uniq'),
        ),
        migrations.AddIndex(
            model_name='nivelinstanciaworkflow',
            index=models.Index(fields=['empresa', 'estado'], name='wf_nivinst_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='nivelinstanciaworkflow',
            constraint=models.UniqueConstraint(fields=('ronda', 'numero'), name='wf_nivinst_ronda_num_uniq'),
        ),
        migrations.AddConstraint(
            model_name='nivelinstanciaworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('instancia',), name='wf_nivinst_activo_uniq'),
        ),
        migrations.AddIndex(
            model_name='decisionaprobacion',
            index=models.Index(fields=['nivel_instancia', 'decision'], name='wf_decision_nivel_idx'),
        ),
        migrations.AddConstraint(
            model_name='decisionaprobacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'idempotency_key'), name='wf_decision_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='decisionaprobacion',
            constraint=models.UniqueConstraint(fields=('asignacion', 'ronda'), name='wf_decision_asig_ronda_uniq'),
        ),
    ]
