# Generated by Django 6.0.4 on 2026-07-31 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduces', '0028_empresa_modulo_workflow'),
        ('workflow', '0002_instanciaworkflow_nivelinstanciaworkflow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroWorkflowEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_codigo', models.CharField(blank=True, max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_workflow', to='conduces.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_workflow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'activo'], name='wf_miembro_emp_act_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'usuario'), name='wf_miembro_emp_usuario_uniq')],
            },
        ),
    ]
