# Generated by Django 6.0.4 on 2026-08-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conduces', '0029_empresa_modulo_inabie'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('valor_recuperado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('motivo', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=20)),
                ('vida_util_meses', models.PositiveIntegerField()),
                ('tasa_residual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponenteActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vida_util_meses', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DepreciacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('acumulada', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_libros', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=30)),
                ('archivo', models.FileField(upload_to='activos/documentos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarantiaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.CharField(max_length=150)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=40)),
                ('snapshot', models.JSONField(default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MejoraActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('descripcion', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevaluacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_nuevo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('motivo', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeguroActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aseguradora', models.CharField(max_length=150)),
                ('poliza', models.CharField(max_length=60)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('cobertura', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UbicacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('fecha_adquisicion', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metodo', models.CharField(default='LINEA_RECTA', max_length=20)),
                ('vida_util_meses', models.PositiveIntegerField()),
                ('estado', models.CharField(default='ACTIVO', max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField(null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.activofijo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
