# Generated by Django 6.0.4 on 2026-08-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('conduces', '0029_empresa_modulo_inabie'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactivo',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='asignacionactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='bajaactivo',
            name='activo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='activos.activofijo'),
        ),
        migrations.AddField(
            model_name='bajaactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='categoriaactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.categoriaactivo'),
        ),
        migrations.AddField(
            model_name='componenteactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='activos.activofijo'),
        ),
        migrations.AddField(
            model_name='depreciacionactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciaciones', to='activos.activofijo'),
        ),
        migrations.AddField(
            model_name='depreciacionactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='documentoactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_activo', to='activos.activofijo'),
        ),
        migrations.AddField(
            model_name='documentoactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='garantiaactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='activos.activofijo'),
        ),
        migrations.AddField(
            model_name='garantiaactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='historialactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='activos.activofijo'),
        ),
        migrations.AddField(
            model_name='mejoraactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.activofijo'),
        ),
        migrations.AddField(
            model_name='mejoraactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.activofijo'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='revaluacionactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.activofijo'),
        ),
        migrations.AddField(
            model_name='revaluacionactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='seguroactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguros', to='activos.activofijo'),
        ),
        migrations.AddField(
            model_name='seguroactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='ubicacionactivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='activos.ubicacionactivo'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='activos.ubicacionactivo'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.ubicacionactivo'),
        ),
    ]
