# Generated by Django 6.0.4 on 2026-07-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_expediente_rfq_enterprise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedientecompra',
            options={'permissions': [('abrir_expedientecompra', 'Puede abrir expedientes'), ('cancelar_expedientecompra', 'Puede cancelar expedientes'), ('declarar_desierto_expedientecompra', 'Puede declarar expedientes desiertos'), ('recalcular_salud_expedientecompra', 'Puede recalcular salud'), ('view_historial_expedientecompra', 'Puede ver historial de expedientes'), ('exportar_expedientecompra', 'Puede exportar expedientes'), ('administrar_expedientecompra', 'Puede administrar expedientes')]},
        ),
        migrations.AlterModelOptions(
            name='invitacionproveedorrfq',
            options={'permissions': [('gestionar_invitacionrfq', 'Puede gestionar invitaciones RFQ'), ('marcar_enviada_invitacionrfq', 'Puede marcar invitación enviada'), ('confirmar_participacion_rfq', 'Puede confirmar participación'), ('registrar_declinacion_rfq', 'Puede registrar declinación'), ('marcar_sin_respuesta_rfq', 'Puede marcar sin respuesta'), ('retirar_proveedor_rfq', 'Puede retirar proveedor RFQ')]},
        ),
        migrations.AlterModelOptions(
            name='procesorfq',
            options={'permissions': [('enviar_revision_rfq', 'Puede enviar RFQ a revisión'), ('devolver_borrador_rfq', 'Puede devolver RFQ a borrador'), ('publicar_rfq', 'Puede publicar RFQ'), ('abrir_rfq', 'Puede abrir RFQ'), ('extender_rfq', 'Puede extender RFQ'), ('cerrar_rfq', 'Puede cerrar RFQ'), ('cancelar_rfq', 'Puede cancelar RFQ'), ('versionar_rfq', 'Puede versionar RFQ'), ('gestionar_criterios_rfq', 'Puede gestionar criterios RFQ'), ('gestionar_reglas_rfq', 'Puede gestionar reglas RFQ'), ('gestionar_proveedores_rfq', 'Puede gestionar proveedores RFQ'), ('exportar_rfq', 'Puede exportar RFQ')]},
        ),
    ]
