# Generated by Django 6.0.4 on 2026-08-04 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_comparativocompra_adjudicacioncompra_and_more'),
        ('conduces', '0029_empresa_modulo_inabie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('RECEPCION', 'Recepcion'), ('FACTURA_PAGO', 'Factura Pago')], max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado'), ('FALLIDO', 'Fallido')], default='ACTIVO', max_length=12)),
                ('paso_actual', models.PositiveSmallIntegerField(default=1)),
                ('total_pasos', models.PositiveSmallIntegerField()),
                ('clave_idempotencia', models.CharField(max_length=180)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('resultado_tipo', models.CharField(blank=True, max_length=80)),
                ('resultado_id', models.CharField(blank=True, max_length=80)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('expira_en', models.DateTimeField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduces.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('operar_wizard_p2p', 'Puede operar wizards P2P')],
            },
        ),
        migrations.CreateModel(
            name='WizardAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=30)),
                ('paso', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata_segura', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='compras.wizardsession')),
            ],
            options={
                'ordering': ['fecha'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='WizardStepState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='PENDIENTE', max_length=12)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='compras.wizardsession')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='wizardsession',
            constraint=models.UniqueConstraint(fields=('empresa', 'usuario', 'tipo', 'clave_idempotencia'), name='p2p_wizard_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='wizardstepstate',
            constraint=models.UniqueConstraint(fields=('sesion', 'numero'), name='p2p_wizard_step_uniq'),
        ),
    ]
