# Generated by Django 6.0.4 on 2026-09-16 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_tasacambio'),
        ('compras', '0006_wizardsession_wizardaudittrail_wizardstepstate_and_more'),
        ('conduces', '0046_centro_matriculas_por_dia'),
        ('workflow', '0003_miembroworkflowempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompraenterprise',
            name='cantidad_por_empaque',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='detalleordencompraenterprise',
            name='disponible_base',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detalleordencompraenterprise',
            name='empaques_sugeridos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleordencompraenterprise',
            name='necesidad_base',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detalleordencompraenterprise',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='detalleordencompraenterprise',
            name='sugerido_base',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detalleordencompraenterprise',
            name='traza',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ordencompraenterprise',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompraenterprise',
            name='periodo_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompraenterprise',
            name='periodo_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompraenterprise',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_enterprise', to='compras.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='ordencompraenterprise',
            constraint=models.UniqueConstraint(condition=models.Q(('origen', 'INABIE')), fields=('empresa', 'origen', 'periodo_desde', 'periodo_hasta'), name='p2p_orden_inabie_periodo_uniq'),
        ),
    ]
