from django.conf import settings
from django.db import models
from django.db.models import Q

class EmpresaBase(models.Model):
    empresa=models.ForeignKey("conduces.Empresa",on_delete=models.CASCADE);creado_por=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True,related_name="+");creado_en=models.DateTimeField(auto_now_add=True)
    class Meta:abstract=True
class PlanCuenta(EmpresaBase):
    codigo=models.CharField(max_length=20);nombre=models.CharField(max_length=150);version=models.PositiveIntegerField(default=1);activo=models.BooleanField(default=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","codigo","version"],name="fin_plan_emp_cod_ver_uniq")]
class CuentaContable(EmpresaBase):
    TIPOS=[(x,x.title()) for x in ("ACTIVO","PASIVO","PATRIMONIO","INGRESO","COSTO","GASTO","ORDEN")]
    plan=models.ForeignKey(PlanCuenta,on_delete=models.PROTECT,related_name="cuentas");padre=models.ForeignKey("self",on_delete=models.PROTECT,null=True,blank=True,related_name="hijas");codigo=models.CharField(max_length=30);nombre=models.CharField(max_length=180);tipo=models.CharField(max_length=12,choices=TIPOS);naturaleza=models.CharField(max_length=7,choices=[("DEBITO","Débito"),("CREDITO","Crédito")]);acepta_movimientos=models.BooleanField(default=True);es_control=models.BooleanField(default=False);requiere_centro_costo=models.BooleanField(default=False);requiere_proyecto=models.BooleanField(default=False);activa=models.BooleanField(default=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","plan","codigo"],name="fin_cuenta_emp_plan_cod_uniq")]
class PeriodoContable(EmpresaBase):
    anio=models.PositiveIntegerField();mes=models.PositiveSmallIntegerField();fecha_inicio=models.DateField();fecha_fin=models.DateField();estado=models.CharField(max_length=10,choices=[("ABIERTO","Abierto"),("CERRADO","Cerrado")],default="ABIERTO")
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","anio","mes"],name="fin_periodo_emp_anio_mes_uniq")]
class DiarioContable(EmpresaBase):
    codigo=models.CharField(max_length=20);nombre=models.CharField(max_length=120);tipo=models.CharField(max_length=20,default="GENERAL");activo=models.BooleanField(default=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","codigo"],name="fin_diario_emp_cod_uniq")]
class LoteContable(EmpresaBase):
    numero=models.CharField(max_length=30);origen=models.CharField(max_length=40);estado=models.CharField(max_length=15,default="BORRADOR")
class AsientoContable(EmpresaBase):
    numero=models.CharField(max_length=30);periodo=models.ForeignKey(PeriodoContable,on_delete=models.PROTECT);diario=models.ForeignKey(DiarioContable,on_delete=models.PROTECT);lote=models.ForeignKey(LoteContable,on_delete=models.PROTECT,null=True,blank=True);fecha=models.DateField();concepto=models.CharField(max_length=255);moneda=models.ForeignKey("catalogos.MonedaEmpresa",on_delete=models.PROTECT,null=True,blank=True);tasa_cambio=models.DecimalField(max_digits=18,decimal_places=6,default=1);estado=models.CharField(max_length=15,choices=[("BORRADOR","Borrador"),("CONTABILIZADO","Contabilizado"),("REVERSADO","Reversado")],default="BORRADOR");origen_tipo=models.CharField(max_length=50,blank=True);origen_id=models.CharField(max_length=50,blank=True);clave_idempotencia=models.CharField(max_length=180,unique=True);total_debito=models.DecimalField(max_digits=18,decimal_places=2,default=0);total_credito=models.DecimalField(max_digits=18,decimal_places=2,default=0)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","numero"],name="fin_asiento_emp_num_uniq")];permissions=[("contabilizar_asiento","Puede contabilizar asientos"),("cerrar_periodo_contable","Puede cerrar períodos")]
class DimensionContable(EmpresaBase):
    codigo=models.CharField(max_length=20);nombre=models.CharField(max_length=100);activa=models.BooleanField(default=True)
class ValorDimensionContable(EmpresaBase):
    dimension=models.ForeignKey(DimensionContable,on_delete=models.CASCADE,related_name="valores");codigo=models.CharField(max_length=30);nombre=models.CharField(max_length=150);activo=models.BooleanField(default=True)
class LineaAsientoContable(models.Model):
    asiento=models.ForeignKey(AsientoContable,on_delete=models.CASCADE,related_name="lineas");cuenta=models.ForeignKey(CuentaContable,on_delete=models.PROTECT);descripcion=models.CharField(max_length=255,blank=True);debito=models.DecimalField(max_digits=18,decimal_places=2,default=0);credito=models.DecimalField(max_digits=18,decimal_places=2,default=0);dimensiones=models.JSONField(default=dict,blank=True)
    class Meta:constraints=[models.CheckConstraint(condition=(Q(debito__gt=0,credito=0)|Q(credito__gt=0,debito=0)),name="fin_linea_un_lado")]
class PlantillaAsiento(EmpresaBase):
    codigo=models.CharField(max_length=30);nombre=models.CharField(max_length=150);lineas=models.JSONField(default=list);activa=models.BooleanField(default=True)
class ReglaContabilizacion(EmpresaBase):
    evento=models.CharField(max_length=60);version=models.PositiveIntegerField(default=1);configuracion=models.JSONField(default=dict);activa=models.BooleanField(default=True)
class CierreContable(EmpresaBase):
    periodo=models.OneToOneField(PeriodoContable,on_delete=models.PROTECT);fecha=models.DateTimeField(auto_now_add=True);motivo=models.TextField(blank=True)
class ReversionContable(EmpresaBase):
    asiento_origen=models.OneToOneField(AsientoContable,on_delete=models.PROTECT,related_name="reversion");asiento_reversion=models.OneToOneField(AsientoContable,on_delete=models.PROTECT,related_name="reversa_de");motivo=models.TextField()
class HistorialAsiento(models.Model):
    asiento=models.ForeignKey(AsientoContable,on_delete=models.CASCADE,related_name="historial");estado_anterior=models.CharField(max_length=15);estado_nuevo=models.CharField(max_length=15);usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);fecha=models.DateTimeField(auto_now_add=True)
class FacturaProveedor(EmpresaBase):
    ESTADOS=[(x,x.replace("_"," ").title()) for x in ("BORRADOR","REGISTRADA","VALIDADA","OBSERVADA","PARCIALMENTE_PAGADA","PAGADA","VENCIDA","ANULADA","EN_DISPUTA")]
    proveedor=models.ForeignKey("compras.Proveedor",on_delete=models.PROTECT);orden=models.ForeignKey("compras.OrdenCompraEnterprise",on_delete=models.PROTECT,null=True,blank=True,related_name="facturas");recepcion=models.ForeignKey("compras.RecepcionCompra",on_delete=models.PROTECT,null=True,blank=True,related_name="facturas");numero=models.CharField(max_length=50);ncf=models.CharField(max_length=30,blank=True);fecha=models.DateField();vence_el=models.DateField();moneda=models.ForeignKey("catalogos.MonedaEmpresa",on_delete=models.PROTECT);tasa_cambio=models.DecimalField(max_digits=18,decimal_places=6,default=1);subtotal=models.DecimalField(max_digits=18,decimal_places=2);descuentos=models.DecimalField(max_digits=18,decimal_places=2,default=0);impuesto=models.DecimalField(max_digits=18,decimal_places=2,default=0);retenciones=models.DecimalField(max_digits=18,decimal_places=2,default=0);cargos=models.DecimalField(max_digits=18,decimal_places=2,default=0);anticipos_aplicados=models.DecimalField(max_digits=18,decimal_places=2,default=0);total=models.DecimalField(max_digits=18,decimal_places=2);estado=models.CharField(max_length=25,choices=ESTADOS,default="BORRADOR");dimensiones=models.JSONField(default=dict,blank=True);version=models.PositiveIntegerField(default=1)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","proveedor","numero"],name="fin_facprov_uniq")]
class DetalleFacturaProveedor(models.Model):
    factura=models.ForeignKey(FacturaProveedor,on_delete=models.CASCADE,related_name="detalles");detalle_orden=models.ForeignKey("compras.DetalleOrdenCompraEnterprise",on_delete=models.PROTECT,null=True,blank=True);descripcion=models.CharField(max_length=255);cantidad=models.DecimalField(max_digits=14,decimal_places=4);precio=models.DecimalField(max_digits=18,decimal_places=4);descuento=models.DecimalField(max_digits=18,decimal_places=2,default=0);impuesto=models.DecimalField(max_digits=18,decimal_places=2,default=0);total=models.DecimalField(max_digits=18,decimal_places=2)
class CuentaPorPagarEnterprise(EmpresaBase):
    factura=models.OneToOneField(FacturaProveedor,on_delete=models.PROTECT,related_name="cuenta_pagar");proveedor=models.ForeignKey("compras.Proveedor",on_delete=models.PROTECT);moneda=models.ForeignKey("catalogos.MonedaEmpresa",on_delete=models.PROTECT);tasa_cambio=models.DecimalField(max_digits=18,decimal_places=6,default=1);monto_original=models.DecimalField(max_digits=18,decimal_places=2);saldo=models.DecimalField(max_digits=18,decimal_places=2);vence_el=models.DateField();estado=models.CharField(max_length=15,default="PENDIENTE");bucket_aging=models.CharField(max_length=12,default="CORRIENTE");bloqueada=models.BooleanField(default=False);motivo_bloqueo=models.TextField(blank=True)
class MovimientoCxP(models.Model):
    cuenta=models.ForeignKey(CuentaPorPagarEnterprise,on_delete=models.CASCADE,related_name="movimientos");tipo=models.CharField(max_length=20);monto=models.DecimalField(max_digits=18,decimal_places=2);saldo_anterior=models.DecimalField(max_digits=18,decimal_places=2);saldo_posterior=models.DecimalField(max_digits=18,decimal_places=2);fecha=models.DateTimeField(auto_now_add=True)
class CuotaCxP(models.Model):
    cuenta=models.ForeignKey(CuentaPorPagarEnterprise,on_delete=models.CASCADE,related_name="cuotas");numero=models.PositiveIntegerField();vence_el=models.DateField();monto=models.DecimalField(max_digits=18,decimal_places=2);saldo=models.DecimalField(max_digits=18,decimal_places=2)
class NotaCreditoProveedor(EmpresaBase):
    factura=models.ForeignKey(FacturaProveedor,on_delete=models.PROTECT,related_name="notas_credito");numero=models.CharField(max_length=30);monto=models.DecimalField(max_digits=18,decimal_places=2);saldo_disponible=models.DecimalField(max_digits=18,decimal_places=2,default=0);impuesto=models.DecimalField(max_digits=18,decimal_places=2,default=0);retencion=models.DecimalField(max_digits=18,decimal_places=2,default=0);tasa_cambio_snapshot=models.DecimalField(max_digits=18,decimal_places=6,default=1);motivo=models.TextField();estado=models.CharField(max_length=24,default="REGISTRADA");asiento_id=models.PositiveBigIntegerField(null=True,blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","factura","numero"],name="fin_ncprov_emp_fac_num_uniq")]
class NotaDebitoProveedor(EmpresaBase):
    factura=models.ForeignKey(FacturaProveedor,on_delete=models.PROTECT,related_name="notas_debito");numero=models.CharField(max_length=30);monto=models.DecimalField(max_digits=18,decimal_places=2);impuesto=models.DecimalField(max_digits=18,decimal_places=2,default=0);tasa_cambio_snapshot=models.DecimalField(max_digits=18,decimal_places=6,default=1);concepto=models.CharField(max_length=15,default="RECARGO");motivo=models.TextField();estado=models.CharField(max_length=24,default="REGISTRADA");asiento_id=models.PositiveBigIntegerField(null=True,blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","factura","numero"],name="fin_ndprov_emp_fac_num_uniq")]
class AplicacionNotaProveedor(models.Model):
    nota_credito=models.ForeignKey(NotaCreditoProveedor,on_delete=models.PROTECT,null=True,blank=True,related_name="aplicaciones");nota_debito=models.ForeignKey(NotaDebitoProveedor,on_delete=models.PROTECT,null=True,blank=True,related_name="aplicaciones");cuenta=models.ForeignKey(CuentaPorPagarEnterprise,on_delete=models.PROTECT,related_name="aplicaciones_notas");monto=models.DecimalField(max_digits=18,decimal_places=2);tasa_cambio=models.DecimalField(max_digits=18,decimal_places=6,default=1);diferencia_cambiaria=models.DecimalField(max_digits=18,decimal_places=2,default=0);clave_idempotencia=models.CharField(max_length=180);asiento_id=models.PositiveBigIntegerField(null=True,blank=True);revertida=models.BooleanField(default=False);fecha=models.DateTimeField(auto_now_add=True)
    class Meta:constraints=[models.CheckConstraint(condition=(Q(nota_credito__isnull=False,nota_debito__isnull=True)|Q(nota_credito__isnull=True,nota_debito__isnull=False)),name="fin_aplic_nota_un_tipo"),models.UniqueConstraint(fields=["cuenta","clave_idempotencia"],name="fin_aplic_nota_idem_uniq")]
class HistorialNotaProveedor(models.Model):
    nota_credito=models.ForeignKey(NotaCreditoProveedor,on_delete=models.CASCADE,null=True,blank=True,related_name="historial");nota_debito=models.ForeignKey(NotaDebitoProveedor,on_delete=models.CASCADE,null=True,blank=True,related_name="historial");estado_anterior=models.CharField(max_length=24);estado_nuevo=models.CharField(max_length=24);usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);comentario=models.TextField(blank=True);fecha=models.DateTimeField(auto_now_add=True)
    class Meta:default_permissions=("view",);ordering=["fecha"]
class AnticipoProveedor(EmpresaBase):
    proveedor=models.ForeignKey("compras.Proveedor",on_delete=models.PROTECT);moneda=models.ForeignKey("catalogos.MonedaEmpresa",on_delete=models.PROTECT);monto=models.DecimalField(max_digits=18,decimal_places=2);saldo=models.DecimalField(max_digits=18,decimal_places=2);tasa_cambio_snapshot=models.DecimalField(max_digits=18,decimal_places=6,default=1);estado=models.CharField(max_length=24,default="DISPONIBLE");referencia=models.CharField(max_length=100,blank=True)
class AplicacionAnticipoProveedor(models.Model):
    anticipo=models.ForeignKey(AnticipoProveedor,on_delete=models.PROTECT,related_name="aplicaciones");cuenta=models.ForeignKey(CuentaPorPagarEnterprise,on_delete=models.PROTECT,related_name="aplicaciones_anticipo");monto=models.DecimalField(max_digits=18,decimal_places=2);tasa_cambio=models.DecimalField(max_digits=18,decimal_places=6,default=1);diferencia_cambiaria=models.DecimalField(max_digits=18,decimal_places=2,default=0);revertida=models.BooleanField(default=False);clave_idempotencia=models.CharField(max_length=180);fecha=models.DateTimeField(auto_now_add=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["anticipo","clave_idempotencia"],name="fin_aplic_ant_idem_uniq")]
class SolicitudPago(EmpresaBase):
    cuenta=models.ForeignKey(CuentaPorPagarEnterprise,on_delete=models.PROTECT);monto=models.DecimalField(max_digits=18,decimal_places=2);estado=models.CharField(max_length=15,default="BORRADOR")
    fecha_prevista=models.DateField(null=True,blank=True);prioridad=models.CharField(max_length=10,choices=[("BAJA","Baja"),("MEDIA","Media"),("ALTA","Alta"),("URGENTE","Urgente")],default="MEDIA");cuenta_prevista=models.ForeignKey("tesoreria.CuentaBancariaEmpresa",on_delete=models.PROTECT,null=True,blank=True,related_name="pagos_programados");observacion=models.TextField(blank=True)
class OrdenPago(EmpresaBase):
    METODOS=[(x,x.title()) for x in ("TRANSFERENCIA","CHEQUE","DEPOSITO","COMPENSACION")];numero=models.CharField(max_length=30);solicitud=models.OneToOneField(SolicitudPago,on_delete=models.PROTECT);estado=models.CharField(max_length=15,default="BORRADOR");metodo=models.CharField(max_length=20,choices=METODOS,default="TRANSFERENCIA");referencia=models.CharField(max_length=100,blank=True);retencion=models.DecimalField(max_digits=18,decimal_places=2,default=0);movimiento_tesoreria_id=models.PositiveBigIntegerField(null=True,blank=True)
class AplicacionPago(models.Model):
    orden=models.ForeignKey(OrdenPago,on_delete=models.PROTECT,related_name="aplicaciones");cuenta=models.ForeignKey(CuentaPorPagarEnterprise,on_delete=models.PROTECT);monto=models.DecimalField(max_digits=18,decimal_places=2)
class PagoMasivo(EmpresaBase):
    numero=models.CharField(max_length=30);estado=models.CharField(max_length=15,default="BORRADOR");total=models.DecimalField(max_digits=18,decimal_places=2,default=0);procesados=models.PositiveIntegerField(default=0);fallidos=models.PositiveIntegerField(default=0);resultado=models.JSONField(default=dict)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","numero"],name="fin_pago_masivo_num_uniq")]
class HistorialCxP(models.Model):
    cuenta=models.ForeignKey(CuentaPorPagarEnterprise,on_delete=models.CASCADE,related_name="historial");estado_anterior=models.CharField(max_length=15);estado_nuevo=models.CharField(max_length=15);fecha=models.DateTimeField(auto_now_add=True)

class CompensacionP2P(EmpresaBase):
    ESTADOS=[(x,x.title()) for x in ("BORRADOR","PROPUESTA","APROBADA","APLICADA","REVERSADA","ANULADA")]
    numero=models.CharField(max_length=30);cuenta_pagar=models.ForeignKey(CuentaPorPagarEnterprise,on_delete=models.PROTECT,related_name="compensaciones");cuenta_cobrar_id=models.PositiveBigIntegerField(null=True,blank=True);anticipo=models.ForeignKey(AnticipoProveedor,on_delete=models.PROTECT,null=True,blank=True);nota_credito=models.ForeignKey(NotaCreditoProveedor,on_delete=models.PROTECT,null=True,blank=True);moneda=models.ForeignKey("catalogos.MonedaEmpresa",on_delete=models.PROTECT);tasa_cambio=models.DecimalField(max_digits=18,decimal_places=6,default=1);monto=models.DecimalField(max_digits=18,decimal_places=2);monto_base=models.DecimalField(max_digits=18,decimal_places=2);diferencia_cambiaria=models.DecimalField(max_digits=18,decimal_places=2,default=0);estado=models.CharField(max_length=12,choices=ESTADOS,default="BORRADOR");clave_idempotencia=models.CharField(max_length=180);asiento_id=models.PositiveBigIntegerField(null=True,blank=True);motivo_reversion=models.TextField(blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","numero"],name="fin_comp_p2p_num_uniq"),models.UniqueConstraint(fields=["empresa","clave_idempotencia"],name="fin_comp_p2p_idem_uniq")];permissions=[("aplicar_compensacion_p2p","Puede aplicar compensaciones P2P"),("revertir_compensacion_p2p","Puede revertir compensaciones P2P")]

class HistorialCompensacionP2P(models.Model):
    compensacion=models.ForeignKey(CompensacionP2P,on_delete=models.CASCADE,related_name="historial");estado_anterior=models.CharField(max_length=12);estado_nuevo=models.CharField(max_length=12);usuario=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True);comentario=models.TextField(blank=True);fecha=models.DateTimeField(auto_now_add=True)

class RetencionProveedor(EmpresaBase):
    TIPOS=[("ITBIS","ITBIS"),("ISR","ISR"),("OTRA","Otra")];ESTADOS=[(x,x.replace("_"," ").title()) for x in ("BORRADOR","PENDIENTE_APROBACION","APROBADA","RECHAZADA","APLICADA","ANULADA","REVERTIDA")]
    numero=models.CharField(max_length=30);proveedor=models.ForeignKey("compras.Proveedor",on_delete=models.PROTECT);factura=models.ForeignKey(FacturaProveedor,on_delete=models.PROTECT,null=True,blank=True,related_name="retenciones_aplicadas");orden_pago=models.ForeignKey(OrdenPago,on_delete=models.PROTECT,null=True,blank=True,related_name="retenciones_aplicadas");tipo=models.CharField(max_length=10,choices=TIPOS);codigo=models.CharField(max_length=30);base=models.DecimalField(max_digits=18,decimal_places=2);tasa=models.DecimalField(max_digits=9,decimal_places=6);monto=models.DecimalField(max_digits=18,decimal_places=2);saldo=models.DecimalField(max_digits=18,decimal_places=2);moneda=models.ForeignKey("catalogos.MonedaEmpresa",on_delete=models.PROTECT,null=True,blank=True);tasa_cambio_snapshot=models.DecimalField(max_digits=18,decimal_places=6,default=1);configuracion_snapshot=models.JSONField(default=dict,blank=True);vigente_desde=models.DateField(null=True,blank=True);vigente_hasta=models.DateField(null=True,blank=True);estado=models.CharField(max_length=24,choices=ESTADOS,default="BORRADOR");clave_idempotencia=models.CharField(max_length=180);asiento_id=models.PositiveBigIntegerField(null=True,blank=True);fecha=models.DateField();motivo_reversion=models.TextField(blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","numero"],name="fin_ret_prov_num_uniq"),models.UniqueConstraint(fields=["empresa","clave_idempotencia"],name="fin_ret_prov_idem_uniq")];permissions=[("aplicar_retencion_proveedor","Puede aplicar retenciones"),("revertir_retencion_proveedor","Puede revertir retenciones")]

class AplicacionRetencionProveedor(models.Model):
    retencion=models.ForeignKey(RetencionProveedor,on_delete=models.PROTECT,related_name="aplicaciones");cuenta=models.ForeignKey(CuentaPorPagarEnterprise,on_delete=models.PROTECT,related_name="retenciones");monto=models.DecimalField(max_digits=18,decimal_places=2);saldo_anterior=models.DecimalField(max_digits=18,decimal_places=2);saldo_posterior=models.DecimalField(max_digits=18,decimal_places=2);revertida=models.BooleanField(default=False);fecha=models.DateTimeField(auto_now_add=True)

class CertificadoRetencionProveedor(EmpresaBase):
    retencion=models.OneToOneField(RetencionProveedor,on_delete=models.PROTECT,related_name="certificado");numero=models.CharField(max_length=40);contenido_hash=models.CharField(max_length=64);emitido_en=models.DateTimeField(auto_now_add=True);anulado_en=models.DateTimeField(null=True,blank=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["empresa","numero"],name="fin_cert_ret_num_uniq")];permissions=[("descargar_certificado_retencion","Puede descargar certificados de retencion")]
